//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//   using 3Dmigoto v1.4.1 on Fri Jun 26 17:23:13 2026
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xyzw        0     NONE   float   xy w
// SV_POSITION              0   xyzw        1      POS   float   xy
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[220], immediateIndexed
dcl_constantbuffer CB1[8], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_sampler s3, mode_default
dcl_sampler s4, mode_default
dcl_sampler s5, mode_default
dcl_sampler s6, mode_default
dcl_sampler s7, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t3
dcl_resource_texture2d (float,float,float,float) t4
dcl_resource_texture2d (float,float,float,float) t5
dcl_resource_texture2d (float,float,float,float) t6
dcl_resource_texture2d (float,float,float,float) t7
dcl_resource_texture2d (float,float,float,float) t8
dcl_resource_texture2d (uint,uint,uint,uint) t9
dcl_input_ps linear v0.xyw
dcl_input_ps_siv linear noperspective v1.xy, position
dcl_output o0.xyzw
dcl_temps 20
div r0.xy, v0.xyxx, v0.wwww
mad r0.zw, r0.xxxy, cb0[66].xxxy, cb0[66].wwwz
sample_l_indexable(texture2d)(float,float,float,float) r1.xyzw, r0.zwzz, t3.xyzw, s3, l(0.000000)
mul r2.xy, r0.zwzz, cb0[131].xyxx
ftou r2.xy, r2.xyxx
mul r1.w, r1.w, l(255.000000)
round_ne r1.w, r1.w
ftou r1.w, r1.w
and r3.x, r1.w, l(15)
ult r3.y, l(0), r3.x
mov r2.zw, l(0,0,0,0)
ld_indexable(texture2d)(uint,uint,uint,uint) r2.z, r2.xyzw, t9.yzxw
and r2.z, r2.z, cb1[2].y
ine r2.z, r2.z, l(0)
and r2.z, r2.z, r3.y
if_nz r2.z
  sample_l_indexable(texture2d)(float,float,float,float) r3.yzw, r0.zwzz, t2.wxyz, s2, l(0.000000)
  sample_l_indexable(texture2d)(float,float,float,float) r4.xyzw, r0.zwzz, t5.xyzw, s5, l(0.000000)
  sample_l_indexable(texture2d)(float,float,float,float) r2.z, r0.zwzz, t1.yzxw, s1, l(0.000000)
  mad r2.w, r2.z, cb0[65].x, cb0[65].y
  mad r2.z, r2.z, cb0[65].z, -cb0[65].w
  div r2.z, l(1.000000, 1.000000, 1.000000, 1.000000), r2.z
  add r2.z, r2.z, r2.w
  mad r3.yzw, r3.yyzw, l(0.000000, 2.000000, 2.000000, 2.000000), l(0.000000, -1.000000, -1.000000, -1.000000)
  dp3 r2.w, r3.yzwy, r3.yzwy
  rsq r2.w, r2.w
  mul r3.yzw, r2.wwww, r3.yyzw
  and r2.w, r1.w, l(16)
  movc r4.xyzw, r2.wwww, l(0,0,0,0), r4.wxyz
  lt r2.w, cb0[31].w, l(1.000000)
  movc r2.w, r2.w, r2.z, l(1.000000)
  mul r0.xy, r0.xyxx, r2.wwww
  mul r5.xyz, r0.yyyy, cb0[49].xyzx
  mad r5.xyz, r0.xxxx, cb0[48].xyzx, r5.xyzx
  mad r5.xyz, r2.zzzz, cb0[50].xyzx, r5.xyzx
  add r5.xyz, r5.xyzx, cb0[51].xyzx
  add r6.xyz, r5.xyzx, -cb0[67].xyzx
  dp3 r0.x, r6.xyzx, r6.xyzx
  rsq r0.x, r0.x
  mul r6.xyz, r0.xxxx, r6.xyzx
  lt r0.x, cb1[1].z, l(0.000000)
  utof r0.y, cb0[143].y
  mad r7.xy, r0.yyyy, l(32.665001, 11.815000, 0.000000, 0.000000), v1.xyxx
  dp2 r0.y, r7.xyxx, l(0.0671105608, 0.00583714992, 0.000000, 0.000000)
  frc r0.y, r0.y
  mul r0.y, r0.y, l(52.982918)
  frc r0.y, r0.y
  sample_l_indexable(texture2d)(float,float,float,float) r7.xy, r0.zwzz, t7.zwxy, s7, l(0.000000)
  mul r7.xy, r7.xyxx, r7.xyxx
  ieq r2.w, r3.x, l(4)
  if_nz r2.w
    mad r7.zw, r4.xxxw, l(0.000000, 0.000000, 2.000000, 2.000000), l(0.000000, 0.000000, -1.00392163, -1.00392163)
    dp3 r2.w, l(1.000000, 1.000000, 1.000000, 0.000000), |r3.yzwy|
    div r8.xy, r3.yzyy, r2.wwww
    ge r2.w, l(0.000000), r3.w
    add r8.zw, -|r8.yyyx|, l(0.000000, 0.000000, 1.000000, 1.000000)
    ge r9.xy, r8.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
    movc r9.xy, r9.xyxx, l(1.000000,1.000000,0,0), l(-1.000000,-1.000000,0,0)
    mul r8.zw, r8.zzzw, r9.xxxy
    movc r8.xy, r2.wwww, r8.zwzz, r8.xyxx
    add r7.zw, r7.zzzw, r8.xxxy
    dp2 r2.w, l(1.000000, 1.000000, 0.000000, 0.000000), |r7.zwzz|
    add r8.z, -r2.w, l(1.000000)
    lt r2.w, r8.z, l(0.000000)
    add r9.xy, -|r7.wzww|, l(1.000000, 1.000000, 0.000000, 0.000000)
    ge r9.zw, r7.zzzw, l(0.000000, 0.000000, 0.000000, 0.000000)
    movc r9.zw, r9.zzzw, l(0,0,1.000000,1.000000), l(0,0,-1.000000,-1.000000)
    mul r9.xy, r9.zwzz, r9.xyxx
    movc r8.xy, r2.wwww, r9.xyxx, r7.zwzz
    dp3 r2.w, r8.xyzx, r8.xyzx
    rsq r2.w, r2.w
    mul r8.xyz, r2.wwww, r8.xyzx
  else
    mov r8.xyz, r3.yzwy
  endif
  add r9.xyz, -r5.xyzx, cb1[3].xyzx
  dp3 r2.w, r9.xyzx, r9.xyzx
  rsq r2.w, r2.w
  mul r10.xyz, r2.wwww, r9.xyzx
  mul r11.xyz, r9.xyzx, cb1[3].wwww
  dp3 r2.w, r11.xyzx, r11.xyzx
  min r2.w, r2.w, l(1.000000)
  add r2.w, -r2.w, l(1.000000)
  log r2.w, r2.w
  mul r2.w, r2.w, cb1[4].w
  exp r2.w, r2.w
  dp3 r5.w, r10.xyzx, cb1[5].xyzx
  add r5.w, r5.w, -cb1[7].x
  mul_sat r5.w, r5.w, cb1[7].y
  mul r5.w, r5.w, r5.w
  mul r2.w, r2.w, r5.w
  lt r5.w, l(0.000000), r2.w
  if_nz r5.w
    mul r2.z, r2.z, cb0[37].y
    if_nz cb1[2].x
      and r7.zw, r1.wwww, l(0, 0, 32, 64)
      movc r1.w, r7.w, l(0), l(1.000000)
      movc r1.w, r7.z, r1.w, l(1.000000)
      dp4 r5.w, cb1[0].xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
      dp4 r1.w, r1.wwww, cb1[0].xyzw
      add r1.w, r1.w, l(-1.000000)
      mad r1.w, r5.w, r1.w, l(1.000000)
      mul r7.xy, r1.wwww, r7.xyxx
      ult r1.w, l(1), cb1[2].x
      lt r5.w, l(0.000000), |cb1[1].z|
      and r1.w, r1.w, r5.w
      movc r0.x, r0.x, l(1.000000), r2.z
      mul r0.x, r0.x, |cb1[1].z|
      and r0.x, r0.x, r1.w
    else
      sample_l_indexable(texture2d)(float,float,float,float) r7.x, r0.zwzz, t6.xyzw, s6, l(0.000000)
      mov r7.y, l(1.000000)
      mov r0.x, l(0)
    endif
    ult r1.w, cb1[2].x, l(2)
    ieq r7.zw, r3.xxxx, l(0, 0, 9, 7)
    and r1.w, r1.w, r7.w
    or r1.w, r7.z, r1.w
    mul r2.z, r2.z, l(0.200000)
    movc r0.x, r1.w, r2.z, r0.x
    lt r1.w, l(0.000000), r0.x
    if_nz r1.w
      add r0.y, r0.y, l(-0.500000)
      add r5.xyz, r5.xyzx, cb0[70].xyzx
      mul r11.xyzw, r5.yyyy, cb0[1].xyzw
      mad r11.xyzw, r5.xxxx, cb0[0].xyzw, r11.xyzw
      mad r5.xyzw, r5.zzzz, cb0[2].xyzw, r11.xyzw
      add r5.xyzw, r5.xyzw, cb0[3].xyzw
      mul r10.xyz, r0.xxxx, r10.xyzx
      mul r11.xyzw, r10.yyyy, cb0[1].xyzw
      mad r11.xyzw, r10.xxxx, cb0[0].xyzw, r11.xyzw
      mad r10.xyzw, r10.zzzz, cb0[2].xyzw, r11.xyzw
      add r10.xyzw, r5.xyzw, r10.xyzw
      div r11.xyz, r5.xyzx, r5.wwww
      div r10.xyz, r10.xyzx, r10.wwww
      add r10.xyz, -r11.xyzx, r10.xyzx
      mad r12.xy, r11.xyxx, cb0[66].xyxx, cb0[66].wzww
      mul r13.xy, r10.xyxx, cb0[66].xyxx
      mad r5.xy, r0.xxxx, cb0[30].zwzz, r5.zwzz
      div r0.x, r5.x, r5.y
      add r0.x, -r11.z, r0.x
      mul r1.w, |r0.x|, l(0.250000)
      mad r5.xyzw, r0.yyyy, l(0.125000, 0.125000, 0.125000, 0.125000), l(0.125000, 0.250000, 0.375000, 0.500000)
      mov r13.z, r10.z
      mov r12.z, r11.z
      mad r14.xyz, r13.xyzx, r5.xxxx, r12.xyzx
      sample_l_indexable(texture2d)(float,float,float,float) r2.z, r14.xyxx, t1.yzxw, s1, l(0.000000)
      add r2.z, -r2.z, r14.z
      mad r2.z, |r0.x|, l(0.250000), r2.z
      lt r2.z, |r2.z|, r1.w
      movc r2.z, r2.z, r5.x, l(-1.000000)
      mad r14.xyz, r13.xyzx, r5.yyyy, r12.xyzx
      sample_l_indexable(texture2d)(float,float,float,float) r5.x, r14.xyxx, t1.xyzw, s1, l(0.000000)
      add r5.x, -r5.x, r14.z
      mad r5.x, |r0.x|, l(0.250000), r5.x
      lt r5.x, |r5.x|, r1.w
      lt r6.w, r2.z, l(0.000000)
      and r5.x, r5.x, r6.w
      movc r2.z, r5.x, r5.y, r2.z
      mad r14.xyz, r13.xyzx, r5.zzzz, r12.xyzx
      sample_l_indexable(texture2d)(float,float,float,float) r5.x, r14.xyxx, t1.xyzw, s1, l(0.000000)
      add r5.x, -r5.x, r14.z
      mad r5.x, |r0.x|, l(0.250000), r5.x
      lt r5.x, |r5.x|, r1.w
      lt r5.y, r2.z, l(0.000000)
      and r5.x, r5.y, r5.x
      movc r2.z, r5.x, r5.z, r2.z
      mad r5.xyz, r13.xyzx, r5.wwww, r12.xyzx
      sample_l_indexable(texture2d)(float,float,float,float) r5.x, r5.xyxx, t1.xyzw, s1, l(0.000000)
      add r5.x, -r5.x, r5.z
      mad r5.x, |r0.x|, l(0.250000), r5.x
      lt r5.x, |r5.x|, r1.w
      lt r5.y, r2.z, l(0.000000)
      and r5.x, r5.y, r5.x
      movc r2.z, r5.x, r5.w, r2.z
      mad r5.xyzw, r0.yyyy, l(0.125000, 0.125000, 0.125000, 0.125000), l(0.625000, 0.750000, 0.875000, 1.000000)
      mad r14.xyz, r13.xyzx, r5.xxxx, r12.xyzx
      sample_l_indexable(texture2d)(float,float,float,float) r0.y, r14.xyxx, t1.yxzw, s1, l(0.000000)
      add r0.y, -r0.y, r14.z
      mad r0.y, |r0.x|, l(0.250000), r0.y
      lt r0.y, |r0.y|, r1.w
      lt r6.w, r2.z, l(0.000000)
      and r0.y, r0.y, r6.w
      movc r0.y, r0.y, r5.x, r2.z
      mad r14.xyz, r13.xyzx, r5.yyyy, r12.xyzx
      sample_l_indexable(texture2d)(float,float,float,float) r2.z, r14.xyxx, t1.yzxw, s1, l(0.000000)
      add r2.z, -r2.z, r14.z
      mad r2.z, |r0.x|, l(0.250000), r2.z
      lt r2.z, |r2.z|, r1.w
      lt r5.x, r0.y, l(0.000000)
      and r2.z, r2.z, r5.x
      movc r0.y, r2.z, r5.y, r0.y
      mad r14.xyz, r13.xyzx, r5.zzzz, r12.xyzx
      sample_l_indexable(texture2d)(float,float,float,float) r2.z, r14.xyxx, t1.yzxw, s1, l(0.000000)
      add r2.z, -r2.z, r14.z
      mad r2.z, |r0.x|, l(0.250000), r2.z
      lt r2.z, |r2.z|, r1.w
      lt r5.x, r0.y, l(0.000000)
      and r2.z, r2.z, r5.x
      movc r0.y, r2.z, r5.z, r0.y
      mad r5.xyz, r13.xyzx, r5.wwww, r12.xyzx
      sample_l_indexable(texture2d)(float,float,float,float) r2.z, r5.xyxx, t1.yzxw, s1, l(0.000000)
      add r2.z, -r2.z, r5.z
      mad r0.x, |r0.x|, l(0.250000), r2.z
      lt r0.x, |r0.x|, r1.w
      lt r1.w, r0.y, l(0.000000)
      and r0.x, r0.x, r1.w
      movc r0.x, r0.x, r5.w, r0.y
      lt r0.y, l(0.000000), r0.x
      and r0.y, r0.y, l(0x3f800000)
      mad r5.xy, r10.xyxx, r0.xxxx, r11.xyxx
      mad r5.xy, |r5.xyxx|, l(6.000000, 6.000000, 0.000000, 0.000000), l(-5.000000, -5.000000, 0.000000, 0.000000)
      max r5.xy, r5.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
      dp2 r0.x, r5.xyxx, r5.xyxx
      add r0.x, -r0.x, l(1.000000)
      max r0.x, r0.x, l(0.000000)
      mad r0.x, -r0.y, r0.x, l(1.000000)
      mul r7.x, r0.x, r7.x
      or r0.y, r7.z, r7.w
      mad r0.x, r0.x, l(0.500000), l(0.500000)
      mul r0.x, r0.x, r7.y
      movc r7.y, r0.y, r7.y, r0.x
    endif
    add r0.x, r7.y, r7.x
    lt r0.x, l(0.000000), r0.x
    if_nz r0.x
      sample_l_indexable(texture2d)(float,float,float,float) r0.xyzw, r0.zwzz, t4.xyzw, s4, l(0.000000)
      ftou r1.w, cb0[151].x
      iadd r2.x, r2.y, r2.x
      iadd r1.w, r1.w, r2.x
      and r1.w, r1.w, l(1)
      movc r2.x, r7.z, l(0), r1.x
      mul r2.y, r1.y, l(0.080000)
      mad r5.xyz, -r1.yyyy, l(0.080000, 0.080000, 0.080000, 0.000000), r0.xyzx
      mad r5.xyz, r2.xxxx, r5.xyzx, r2.yyyy
      ieq r2.y, r3.x, l(5)
      or r2.y, r7.z, r2.y
      lt r2.z, l(0.000000), cb0[155].x
      lt r6.w, l(0.000000), cb0[200].z
      and r2.z, r2.z, r6.w
      ne r6.w, l(0.000000, 0.000000, 0.000000, 0.000000), cb0[155].x
      movc r10.xyz, r6.wwww, l(1.000000,1.000000,1.000000,0), r0.xyzx
      movc r7.zw, r1.wwww, l(0,0,1.000000,0), l(0,0,0,1.000000)
      mul r11.xyz, r5.xyzx, r7.wwww
      mul r11.w, r1.y, r7.w
      movc r10.xyz, r2.zzzz, r7.zzzz, r10.xyzx
      mov r5.w, r1.y
      movc r11.xyzw, r2.zzzz, r11.xyzw, r5.xyzw
      movc r11.xyz, r2.yyyy, r11.xyzx, r5.xyzx
      mov r10.w, r11.w
      mov r5.xyz, r0.xyzx
      movc r5.xyzw, r2.yyyy, r10.xyzw, r5.xyzw
      mad r0.xyz, -r5.xyzx, r2.xxxx, r5.xyzx
      mad r0.xyz, r0.xyzx, cb0[135].wwww, cb0[135].xyzx
      mad r10.xyz, r11.xyzx, cb0[136].wwww, cb0[136].xyzx
      mul r1.y, cb1[7].w, l(0.500000)
      mad r11.xyz, -r1.yyyy, cb1[6].xyzx, r9.xyzx
      mad r9.xyz, r1.yyyy, cb1[6].xyzx, r9.xyzx
      lt r1.y, l(0.000000), cb1[7].w
      if_nz r1.y
        dp3 r1.w, r11.xyzx, r11.xyzx
        dp3 r2.z, r9.xyzx, r9.xyzx
        rsq r1.w, r1.w
        rsq r2.z, r2.z
        mul r6.w, r1.w, r2.z
        dp3 r7.z, r11.xyzx, r9.xyzx
        mul r7.z, r6.w, r7.z
        mad r7.w, r7.z, l(0.500000), r6.w
        add r7.w, r7.w, l(0.500000)
        div r6.w, r6.w, r7.w
        dp3 r7.w, r8.xyzx, r11.xyzx
        dp3 r8.w, r8.xyzx, r9.xyzx
        mul r2.z, r2.z, r8.w
        mad r1.w, r7.w, r1.w, r2.z
        mul r1.w, r1.w, l(0.500000)
      else
        dp3 r2.z, r11.xyzx, r11.xyzx
        add r7.w, r2.z, l(1.000000)
        rcp r6.w, r7.w
        rsq r2.z, r2.z
        mul r12.xyz, r2.zzzz, r11.xyzx
        dp3 r1.w, r8.xyzx, r12.xyzx
        mov r7.z, l(1.000000)
      endif
      lt r2.z, l(0.000000), cb1[6].w
      mul r7.w, cb1[6].w, cb1[6].w
      mul_sat r6.w, r6.w, r7.w
      sqrt r6.w, r6.w
      lt r7.w, r1.w, r6.w
      max r8.w, r1.w, -r6.w
      add r8.w, r6.w, r8.w
      mul r8.w, r8.w, r8.w
      mul r6.w, r6.w, l(4.000000)
      div r6.w, r8.w, r6.w
      movc r6.w, r7.w, r6.w, r1.w
      movc_sat r1.w, r2.z, r6.w, r1.w
      dp3 r2.z, r6.xyzx, r8.xyzx
      add r2.z, r2.z, r2.z
      mad r12.xyz, r8.xyzx, -r2.zzzz, r6.xyzx
      add r9.xyz, -r11.xyzx, r9.xyzx
      dp3 r2.z, r12.xyzx, r9.xyzx
      mad r12.xyz, r2.zzzz, r12.xyzx, -r9.xyzx
      dp3 r6.w, r11.xyzx, r12.xyzx
      mul r2.z, r2.z, r2.z
      mad r2.z, cb1[7].w, cb1[7].w, -r2.z
      div_sat r2.z, r6.w, r2.z
      mad r9.xyz, r2.zzzz, r9.xyzx, r11.xyzx
      movc r9.xyz, r1.yyyy, r9.xyzx, r11.xyzx
      dp3 r1.y, r9.xyzx, r9.xyzx
      rsq r1.y, r1.y
      mul r11.xyz, r1.yyyy, r9.xyzx
      max r1.z, r1.z, cb0[219].y
      mul r2.z, r1.z, r1.z
      mul r6.w, r1.y, cb1[6].w
      mad r7.w, -r1.z, r1.z, l(1.000000)
      mul_sat r6.w, r6.w, r7.w
      mul_sat r8.w, r1.y, cb1[7].z
      switch r3.x
        case l(1)
        case l(10)
        case l(11)
        dp3 r3.x, r8.xyzx, r11.xyzx
        dp3 r9.w, r8.xyzx, -r6.xyzx
        dp3 r10.w, -r6.xyzx, r11.xyzx
        lt r11.w, l(0.000000), r6.w
        if_nz r11.w
          mad r12.w, -r6.w, r6.w, l(1.000000)
          sqrt r12.w, r12.w
          dp2 r13.w, r9.wwww, r3.xxxx
          add r14.w, -r10.w, r13.w
          ge r15.x, r14.w, r12.w
          if_nz r15.x
            mov r15.x, l(1.000000)
            mov r15.y, |r9.w|
          else
            mad r15.z, -r14.w, r14.w, l(1.000000)
            rsq r15.z, r15.z
            mul r15.z, r6.w, r15.z
            mad r15.w, -r14.w, r3.x, r9.w
            mul r16.x, r15.w, r15.z
            mul r16.y, r9.w, r9.w
            mad r16.y, r16.y, l(2.000000), l(-1.000000)
            mad r14.w, -r14.w, r10.w, r16.y
            mul r14.w, r14.w, r15.z
            mad r16.y, -r3.x, r3.x, l(1.000000)
            mad r16.y, -r9.w, r9.w, r16.y
            mad r16.y, -r10.w, r10.w, r16.y
            mad_sat r13.w, r13.w, r10.w, r16.y
            sqrt r13.w, r13.w
            mul r13.w, r13.w, r15.z
            mul r16.y, r9.w, r13.w
            add r16.z, r16.y, r16.y
            mad r16.w, r3.x, r12.w, r9.w
            mad r15.z, r15.z, r15.w, r16.w
            mad r15.w, r10.w, r12.w, r14.w
            add r15.w, r15.w, l(1.000000)
            mul r17.x, r13.w, r15.w
            mul r17.y, r15.w, r15.z
            mul r17.z, r15.z, r16.z
            mul r16.y, r16.y, r15.z
            mul r16.y, r16.y, l(0.500000)
            mad r16.y, r17.x, l(-0.500000), r16.y
            mul r16.y, r16.y, r17.y
            mad r17.w, -r17.x, l(2.000000), r17.z
            mul r17.z, r17.w, r17.z
            mad r17.x, r17.x, r17.x, r17.z
            mul r17.z, r15.w, r15.w
            mad r15.w, r10.w, r12.w, r15.w
            mad r15.w, r15.w, l(-0.500000), l(-0.500000)
            mul r15.w, r15.w, r17.y
            mad r15.w, r16.w, r17.z, r15.w
            mad r15.z, r15.z, r15.w, r17.x
            add r15.w, r16.y, r16.y
            mul r16.w, r16.y, r16.y
            mad r16.w, r15.z, r15.z, r16.w
            div r15.w, r15.w, r16.w
            mul r15.z, r15.z, r15.w
            mad r15.w, -r15.w, r16.y, l(1.000000)
            mul r13.w, r13.w, r15.z
            mad r13.w, r15.w, r16.x, r13.w
            mul r15.z, r16.z, r15.z
            mad r14.w, r15.w, r14.w, r15.z
            mad r13.w, r3.x, r12.w, r13.w
            mad r12.w, r10.w, r12.w, r14.w
            mad r14.w, r12.w, l(2.000000), l(2.000000)
            rsq r14.w, r14.w
            add r13.w, r9.w, r13.w
            mul_sat r15.x, r14.w, r13.w
            mad_sat r15.y, r14.w, r12.w, r14.w
          endif
        else
          mad r12.w, r10.w, l(2.000000), l(2.000000)
          rsq r12.w, r12.w
          add r3.x, r3.x, r9.w
          mul_sat r15.x, r12.w, r3.x
          mad_sat r15.y, r12.w, r10.w, r12.w
        endif
        add r3.x, |r9.w|, l(0.000010)
        min r3.x, r3.x, l(1.000000)
        mul r16.xyz, r0.xyzx, r1.wwww
        mul r12.xyz, r16.xyzx, l(0.318309873, 0.318309873, 0.318309873, 0.000000)
        mul r9.w, r2.z, r2.z
        lt r10.w, l(0.000000), r8.w
        mul r12.w, r8.w, r8.w
        mad r13.w, r15.y, l(3.600000), l(0.400000)
        div r12.w, r12.w, r13.w
        mad r12.w, r2.z, r2.z, r12.w
        min r12.w, r12.w, l(1.000000)
        movc r16.x, r10.w, r12.w, r9.w
        mul r9.w, r6.w, l(0.250000)
        ishr r10.w, r16.x, l(1)
        iadd r10.w, r10.w, l(0x1fbd1df5)
        mad r10.w, r10.w, l(3.000000), r6.w
        mul r9.w, r9.w, r10.w
        add r10.w, r15.y, l(0.001000)
        div r9.w, r9.w, r10.w
        add r17.x, r9.w, r16.x
        div r17.y, r16.x, r17.x
        mov r16.y, l(1.000000)
        movc r15.zw, r11.wwww, r17.xxxy, r16.xxxy
        lt r9.w, r7.z, l(1.000000)
        add r11.w, -r7.z, l(1.000100)
        add r12.w, r7.z, l(1.000000)
        div r11.w, r11.w, r12.w
        sqrt r11.w, r11.w
        mul r12.w, r11.w, l(0.250000)
        ishr r13.w, r15.z, l(1)
        iadd r13.w, r13.w, l(0x1fbd1df5)
        mad r11.w, r13.w, l(3.000000), r11.w
        mul r11.w, r11.w, r12.w
        div r10.w, r11.w, r10.w
        add r10.w, r10.w, r15.z
        div r10.w, r15.z, r10.w
        sqrt r10.w, r10.w
        mul r10.w, r10.w, r15.w
        movc r9.w, r9.w, r10.w, r15.w
        mad r10.w, r15.x, r16.x, -r15.x
        mad r10.w, r10.w, r15.x, l(1.000000)
        mul r10.w, r10.w, r10.w
        mul r10.w, r10.w, l(3.14159274)
        div r10.w, r16.x, r10.w
        mul r9.w, r9.w, r10.w
        sqrt r10.w, r16.x
        add r11.w, -r10.w, l(1.000000)
        mad r12.w, r3.x, r11.w, r10.w
        mad r10.w, r1.w, r11.w, r10.w
        mul r3.x, r3.x, r10.w
        mad r3.x, r1.w, r12.w, r3.x
        rcp r3.x, r3.x
        mul r3.x, r3.x, r9.w
        add r9.w, -r15.y, l(1.000000)
        mul r10.w, r9.w, r9.w
        mul r10.w, r10.w, r10.w
        mul r11.w, r9.w, r10.w
        mul_sat r12.w, r10.y, l(50.000000)
        mad r9.w, -r10.w, r9.w, l(1.000000)
        mul r15.xyz, r10.xyzx, r9.wwww
        mad r15.xyz, r12.wwww, r11.wwww, r15.xyzx
        mul r3.x, r3.x, l(0.500000)
        mul r15.xyz, r15.xyzx, r3.xxxx
        mul r13.xyz, r1.wwww, r15.xyzx
        mov r14.xyz, l(0,0,0,0)
        break
        case l(2)
        dp3 r3.x, r8.xyzx, r11.xyzx
        dp3 r9.w, r8.xyzx, -r6.xyzx
        dp3 r10.w, -r6.xyzx, r11.xyzx
        lt r11.w, l(0.000000), r6.w
        if_nz r11.w
          mad r12.w, -r6.w, r6.w, l(1.000000)
          sqrt r12.w, r12.w
          dp2 r13.w, r9.wwww, r3.xxxx
          add r14.w, -r10.w, r13.w
          ge r15.x, r14.w, r12.w
          if_nz r15.x
            mov r15.x, l(1.000000)
            mov r15.y, |r9.w|
          else
            mad r15.z, -r14.w, r14.w, l(1.000000)
            rsq r15.z, r15.z
            mul r15.z, r6.w, r15.z
            mad r15.w, -r14.w, r3.x, r9.w
            mul r16.x, r15.w, r15.z
            mul r16.y, r9.w, r9.w
            mad r16.y, r16.y, l(2.000000), l(-1.000000)
            mad r14.w, -r14.w, r10.w, r16.y
            mul r14.w, r14.w, r15.z
            mad r16.y, -r3.x, r3.x, l(1.000000)
            mad r16.y, -r9.w, r9.w, r16.y
            mad r16.y, -r10.w, r10.w, r16.y
            mad_sat r13.w, r13.w, r10.w, r16.y
            sqrt r13.w, r13.w
            mul r13.w, r13.w, r15.z
            mul r16.y, r9.w, r13.w
            add r16.z, r16.y, r16.y
            mad r16.w, r3.x, r12.w, r9.w
            mad r15.z, r15.z, r15.w, r16.w
            mad r15.w, r10.w, r12.w, r14.w
            add r15.w, r15.w, l(1.000000)
            mul r17.x, r13.w, r15.w
            mul r17.y, r15.w, r15.z
            mul r17.z, r15.z, r16.z
            mul r16.y, r16.y, r15.z
            mul r16.y, r16.y, l(0.500000)
            mad r16.y, r17.x, l(-0.500000), r16.y
            mul r16.y, r16.y, r17.y
            mad r17.w, -r17.x, l(2.000000), r17.z
            mul r17.z, r17.w, r17.z
            mad r17.x, r17.x, r17.x, r17.z
            mul r17.z, r15.w, r15.w
            mad r15.w, r10.w, r12.w, r15.w
            mad r15.w, r15.w, l(-0.500000), l(-0.500000)
            mul r15.w, r15.w, r17.y
            mad r15.w, r16.w, r17.z, r15.w
            mad r15.z, r15.z, r15.w, r17.x
            add r15.w, r16.y, r16.y
            mul r16.w, r16.y, r16.y
            mad r16.w, r15.z, r15.z, r16.w
            div r15.w, r15.w, r16.w
            mul r15.z, r15.z, r15.w
            mad r15.w, -r15.w, r16.y, l(1.000000)
            mul r13.w, r13.w, r15.z
            mad r13.w, r15.w, r16.x, r13.w
            mul r15.z, r16.z, r15.z
            mad r14.w, r15.w, r14.w, r15.z
            mad r13.w, r3.x, r12.w, r13.w
            mad r12.w, r10.w, r12.w, r14.w
            mad r14.w, r12.w, l(2.000000), l(2.000000)
            rsq r14.w, r14.w
            add r13.w, r9.w, r13.w
            mul_sat r15.x, r14.w, r13.w
            mad_sat r15.y, r14.w, r12.w, r14.w
          endif
        else
          mad r12.w, r10.w, l(2.000000), l(2.000000)
          rsq r12.w, r12.w
          add r3.x, r3.x, r9.w
          mul_sat r15.x, r12.w, r3.x
          mad_sat r15.y, r12.w, r10.w, r12.w
        endif
        add r3.x, |r9.w|, l(0.000010)
        min r3.x, r3.x, l(1.000000)
        mul r16.xyz, r0.xyzx, r1.wwww
        mul r12.xyz, r16.xyzx, l(0.318309873, 0.318309873, 0.318309873, 0.000000)
        mul r9.w, r2.z, r2.z
        lt r10.w, l(0.000000), r8.w
        mul r12.w, r8.w, r8.w
        mad r13.w, r15.y, l(3.600000), l(0.400000)
        div r12.w, r12.w, r13.w
        mad r12.w, r2.z, r2.z, r12.w
        min r12.w, r12.w, l(1.000000)
        movc r16.x, r10.w, r12.w, r9.w
        mul r9.w, r6.w, l(0.250000)
        ishr r10.w, r16.x, l(1)
        iadd r10.w, r10.w, l(0x1fbd1df5)
        mad r10.w, r10.w, l(3.000000), r6.w
        mul r9.w, r9.w, r10.w
        add r10.w, r15.y, l(0.001000)
        div r9.w, r9.w, r10.w
        add r17.x, r9.w, r16.x
        div r17.y, r16.x, r17.x
        mov r16.y, l(1.000000)
        movc r15.zw, r11.wwww, r17.xxxy, r16.xxxy
        lt r9.w, r7.z, l(1.000000)
        add r11.w, -r7.z, l(1.000100)
        add r12.w, r7.z, l(1.000000)
        div r11.w, r11.w, r12.w
        sqrt r11.w, r11.w
        mul r12.w, r11.w, l(0.250000)
        ishr r13.w, r15.z, l(1)
        iadd r13.w, r13.w, l(0x1fbd1df5)
        mad r11.w, r13.w, l(3.000000), r11.w
        mul r11.w, r11.w, r12.w
        div r10.w, r11.w, r10.w
        add r10.w, r10.w, r15.z
        div r10.w, r15.z, r10.w
        sqrt r10.w, r10.w
        mul r10.w, r10.w, r15.w
        movc r9.w, r9.w, r10.w, r15.w
        mad r10.w, r15.x, r16.x, -r15.x
        mad r10.w, r10.w, r15.x, l(1.000000)
        mul r10.w, r10.w, r10.w
        mul r10.w, r10.w, l(3.14159274)
        div r10.w, r16.x, r10.w
        mul r9.w, r9.w, r10.w
        sqrt r10.w, r16.x
        add r11.w, -r10.w, l(1.000000)
        mad r12.w, r3.x, r11.w, r10.w
        mad r10.w, r1.w, r11.w, r10.w
        mul r3.x, r3.x, r10.w
        mad r3.x, r1.w, r12.w, r3.x
        rcp r3.x, r3.x
        mul r3.x, r3.x, r9.w
        add r9.w, -r15.y, l(1.000000)
        mul r10.w, r9.w, r9.w
        mul r10.w, r10.w, r10.w
        mul r11.w, r9.w, r10.w
        mul_sat r12.w, r10.y, l(50.000000)
        mad r9.w, -r10.w, r9.w, l(1.000000)
        mul r15.xyz, r10.xyzx, r9.wwww
        mad r15.xyz, r12.wwww, r11.wwww, r15.xyzx
        mul r3.x, r3.x, l(0.500000)
        mul r15.xyz, r15.xyzx, r3.xxxx
        mul r13.xyz, r1.wwww, r15.xyzx
        mul r15.xyz, r4.yzwy, r4.yzwy
        mad r16.xyz, r9.xyzx, r1.yyyy, -r6.xyzx
        dp3 r3.x, r16.xyzx, r16.xyzx
        rsq r3.x, r3.x
        mul r16.xyz, r3.xxxx, r16.xyzx
        dp3_sat r3.x, r11.xyzx, r6.xyzx
        log r3.x, r3.x
        mul r3.x, r3.x, l(12.000000)
        exp r3.x, r3.x
        mad r9.w, r4.x, l(-2.900000), l(3.000000)
        mul r3.x, r3.x, r9.w
        dp3 r9.w, r8.xyzx, r16.xyzx
        mad r9.w, r9.w, r4.x, l(1.000000)
        add_sat r9.w, -r4.x, r9.w
        mul r0.w, r0.w, r9.w
        mul r9.w, r0.w, l(0.159154937)
        mad r0.w, -r0.w, l(0.159154937), l(1.000000)
        mad r0.w, r3.x, r0.w, r9.w
        mul r14.xyz, r15.xyzx, r0.wwww
        break
        case l(3)
        dp3 r0.w, r8.xyzx, r11.xyzx
        dp3 r3.x, r8.xyzx, -r6.xyzx
        dp3 r9.w, -r6.xyzx, r11.xyzx
        lt r10.w, l(0.000000), r6.w
        if_nz r10.w
          mad r11.w, -r6.w, r6.w, l(1.000000)
          sqrt r11.w, r11.w
          dp2 r12.w, r3.xxxx, r0.wwww
          add r13.w, -r9.w, r12.w
          ge r14.w, r13.w, r11.w
          if_nz r14.w
            mov r14.w, l(1.000000)
            mov r15.x, |r3.x|
          else
            mad r15.y, -r13.w, r13.w, l(1.000000)
            rsq r15.y, r15.y
            mul r15.y, r6.w, r15.y
            mad r15.z, -r13.w, r0.w, r3.x
            mul r15.w, r15.z, r15.y
            mul r16.x, r3.x, r3.x
            mad r16.x, r16.x, l(2.000000), l(-1.000000)
            mad r13.w, -r13.w, r9.w, r16.x
            mul r13.w, r13.w, r15.y
            mad r16.x, -r0.w, r0.w, l(1.000000)
            mad r16.x, -r3.x, r3.x, r16.x
            mad r16.x, -r9.w, r9.w, r16.x
            mad_sat r12.w, r12.w, r9.w, r16.x
            sqrt r12.w, r12.w
            mul r12.w, r12.w, r15.y
            mul r16.x, r3.x, r12.w
            add r16.y, r16.x, r16.x
            mad r16.z, r0.w, r11.w, r3.x
            mad r15.y, r15.y, r15.z, r16.z
            mad r15.z, r9.w, r11.w, r13.w
            add r15.z, r15.z, l(1.000000)
            mul r16.w, r12.w, r15.z
            mul r17.x, r15.z, r15.y
            mul r17.y, r15.y, r16.y
            mul r16.x, r16.x, r15.y
            mul r16.x, r16.x, l(0.500000)
            mad r16.x, r16.w, l(-0.500000), r16.x
            mul r16.x, r16.x, r17.x
            mad r17.z, -r16.w, l(2.000000), r17.y
            mul r17.y, r17.z, r17.y
            mad r16.w, r16.w, r16.w, r17.y
            mul r17.y, r15.z, r15.z
            mad r15.z, r9.w, r11.w, r15.z
            mad r15.z, r15.z, l(-0.500000), l(-0.500000)
            mul r15.z, r15.z, r17.x
            mad r15.z, r16.z, r17.y, r15.z
            mad r15.y, r15.y, r15.z, r16.w
            add r15.z, r16.x, r16.x
            mul r16.z, r16.x, r16.x
            mad r16.z, r15.y, r15.y, r16.z
            div r15.z, r15.z, r16.z
            mul r15.y, r15.y, r15.z
            mad r15.z, -r15.z, r16.x, l(1.000000)
            mul r12.w, r12.w, r15.y
            mad r12.w, r15.z, r15.w, r12.w
            mul r15.y, r16.y, r15.y
            mad r13.w, r15.z, r13.w, r15.y
            mad r12.w, r0.w, r11.w, r12.w
            mad r11.w, r9.w, r11.w, r13.w
            mad r13.w, r11.w, l(2.000000), l(2.000000)
            rsq r13.w, r13.w
            add r12.w, r3.x, r12.w
            mul_sat r14.w, r13.w, r12.w
            mad_sat r15.x, r13.w, r11.w, r13.w
          endif
        else
          mad r11.w, r9.w, l(2.000000), l(2.000000)
          rsq r11.w, r11.w
          add r12.w, r0.w, r3.x
          mul_sat r14.w, r11.w, r12.w
          mad_sat r15.x, r11.w, r9.w, r11.w
        endif
        add r3.x, |r3.x|, l(0.000010)
        min r3.x, r3.x, l(1.000000)
        mul r15.yzw, r0.xxyz, r1.wwww
        mul r12.xyz, r15.yzwy, l(0.318309873, 0.318309873, 0.318309873, 0.000000)
        mul r9.w, r2.z, r2.z
        lt r11.w, l(0.000000), r8.w
        mul r12.w, r8.w, r8.w
        mad r13.w, r15.x, l(3.600000), l(0.400000)
        div r12.w, r12.w, r13.w
        mad r12.w, r2.z, r2.z, r12.w
        min r12.w, r12.w, l(1.000000)
        movc r16.x, r11.w, r12.w, r9.w
        mul r9.w, r6.w, l(0.250000)
        ishr r11.w, r16.x, l(1)
        iadd r11.w, r11.w, l(0x1fbd1df5)
        mad r11.w, r11.w, l(3.000000), r6.w
        mul r9.w, r9.w, r11.w
        add r11.w, r15.x, l(0.001000)
        div r9.w, r9.w, r11.w
        add r17.x, r9.w, r16.x
        div r17.y, r16.x, r17.x
        mov r16.y, l(1.000000)
        movc r15.yz, r10.wwww, r17.xxyx, r16.xxyx
        lt r9.w, r7.z, l(1.000000)
        add r10.w, -r7.z, l(1.000100)
        add r12.w, r7.z, l(1.000000)
        div r10.w, r10.w, r12.w
        sqrt r10.w, r10.w
        mul r12.w, r10.w, l(0.250000)
        ishr r13.w, r15.y, l(1)
        iadd r13.w, r13.w, l(0x1fbd1df5)
        mad r10.w, r13.w, l(3.000000), r10.w
        mul r10.w, r10.w, r12.w
        div r10.w, r10.w, r11.w
        add r10.w, r10.w, r15.y
        div r10.w, r15.y, r10.w
        sqrt r10.w, r10.w
        mul r10.w, r10.w, r15.z
        movc r9.w, r9.w, r10.w, r15.z
        mad r10.w, r14.w, r16.x, -r14.w
        mad r10.w, r10.w, r14.w, l(1.000000)
        mul r10.w, r10.w, r10.w
        mul r10.w, r10.w, l(3.14159274)
        div r10.w, r16.x, r10.w
        mul r9.w, r9.w, r10.w
        sqrt r10.w, r16.x
        add r11.w, -r10.w, l(1.000000)
        mad r12.w, r3.x, r11.w, r10.w
        mad r10.w, r1.w, r11.w, r10.w
        mul r3.x, r3.x, r10.w
        mad r3.x, r1.w, r12.w, r3.x
        rcp r3.x, r3.x
        mul r3.x, r3.x, r9.w
        add r9.w, -r15.x, l(1.000000)
        mul r10.w, r9.w, r9.w
        mul r10.w, r10.w, r10.w
        mul r11.w, r9.w, r10.w
        mul_sat r12.w, r10.y, l(50.000000)
        mad r9.w, -r10.w, r9.w, l(1.000000)
        mul r15.xyz, r10.xyzx, r9.wwww
        mad r15.xyz, r12.wwww, r11.wwww, r15.xyzx
        mul r3.x, r3.x, l(0.500000)
        mul r15.xyz, r15.xyzx, r3.xxxx
        mul r13.xyz, r1.wwww, r15.xyzx
        mul r15.xyz, r4.yzwy, r4.yzwy
        mad_sat r16.x, r0.w, l(0.500000), l(0.500000)
        add r16.y, -r4.x, l(1.000000)
        sample_l_indexable(texture2d)(float,float,float,float) r16.xyz, r16.xyxx, t0.xyzw, s0, l(0.000000)
        mul r14.xyz, r15.xyzx, r16.xyzx
        break
        case l(4)
        max r0.w, r4.z, l(0.020000)
        dp3 r3.x, r3.yzwy, r11.xyzx
        dp3 r3.y, r3.yzwy, -r6.xyzx
        dp3 r3.z, -r6.xyzx, r11.xyzx
        lt r3.w, l(0.000000), r6.w
        if_nz r3.w
          mad r9.w, -r6.w, r6.w, l(1.000000)
          sqrt r9.w, r9.w
          dp2 r10.w, r3.yyyy, r3.xxxx
          add r10.w, -r3.z, r10.w
          ge r11.w, r10.w, r9.w
          if_nz r11.w
            mov r11.w, l(1.000000)
            mov r15.z, |r3.y|
          else
            mad r12.w, -r10.w, r10.w, l(1.000000)
            rsq r12.w, r12.w
            mul r12.w, r6.w, r12.w
            mad r13.w, -r10.w, r3.x, r3.y
            mul r13.w, r12.w, r13.w
            dp2 r14.w, r3.yyyy, r3.yyyy
            add r14.w, r14.w, l(-1.000000)
            mad r10.w, -r10.w, r3.z, r14.w
            mul r10.w, r10.w, r12.w
            mad r12.w, r3.x, r9.w, r13.w
            mad r3.z, r3.z, r9.w, r10.w
            mad r9.w, r3.z, l(2.000000), l(2.000000)
            rsq r9.w, r9.w
            add r10.w, r3.y, r12.w
            mul_sat r11.w, r9.w, r10.w
            mad_sat r15.z, r9.w, r3.z, r9.w
          endif
        else
          mad r9.w, r3.z, l(2.000000), l(2.000000)
          rsq r9.w, r9.w
          add r3.x, r3.y, r3.x
          mul_sat r11.w, r9.w, r3.x
          mad_sat r15.z, r9.w, r3.z, r9.w
        endif
        add r3.x, |r3.y|, l(0.000010)
        min r3.x, r3.x, l(1.000000)
        add r3.y, -r15.z, l(1.000000)
        mul r9.w, r3.y, r3.y
        mul r9.w, r9.w, r9.w
        mul r10.w, r3.y, r9.w
        mad r3.y, -r9.w, r3.y, l(1.000000)
        mad r3.y, r3.y, l(0.040000), r10.w
        mul r0.w, r0.w, r0.w
        mul r9.w, r0.w, r0.w
        lt r10.w, l(0.000000), r8.w
        mul r12.w, r8.w, r8.w
        mad r13.w, r15.z, l(3.600000), l(0.400000)
        div r13.w, r12.w, r13.w
        mad r0.w, r0.w, r0.w, r13.w
        min r0.w, r0.w, l(1.000000)
        movc r16.x, r10.w, r0.w, r9.w
        mul r0.w, r6.w, l(0.250000)
        ishr r9.w, r16.x, l(1)
        iadd r9.w, r9.w, l(0x1fbd1df5)
        mad r9.w, r9.w, l(3.000000), r6.w
        mul r9.w, r0.w, r9.w
        add r13.w, r15.z, l(0.001000)
        div r9.w, r9.w, r13.w
        add r17.x, r9.w, r16.x
        div r17.y, r16.x, r17.x
        mov r16.yw, l(0,1.000000,0,1.000000)
        movc r17.xy, r3.wwww, r17.xyxx, r16.xyxx
        lt r9.w, r7.z, l(1.000000)
        add r14.w, -r7.z, l(1.000100)
        add r15.w, r7.z, l(1.000000)
        div r14.w, r14.w, r15.w
        sqrt r14.w, r14.w
        mul r15.w, r14.w, l(0.250000)
        ishr r16.y, r17.x, l(1)
        iadd r16.y, r16.y, l(0x1fbd1df5)
        mad r16.y, r16.y, l(3.000000), r14.w
        mul r16.y, r15.w, r16.y
        div r13.w, r16.y, r13.w
        add r13.w, r13.w, r17.x
        div r13.w, r17.x, r13.w
        sqrt r13.w, r13.w
        mul r13.w, r13.w, r17.y
        movc r13.w, r9.w, r13.w, r17.y
        mad r16.y, r11.w, r16.x, -r11.w
        mad r11.w, r16.y, r11.w, l(1.000000)
        mul r11.w, r11.w, r11.w
        mul r11.w, r11.w, l(3.14159274)
        div r11.w, r16.x, r11.w
        mul r11.w, r13.w, r11.w
        sqrt r13.w, r16.x
        add r16.x, -r13.w, l(1.000000)
        mad r16.y, r3.x, r16.x, r13.w
        mad r13.w, r1.w, r16.x, r13.w
        mul r3.x, r3.x, r13.w
        mad r3.x, r1.w, r16.y, r3.x
        rcp r3.x, r3.x
        mul r3.x, r3.x, r11.w
        mul r3.x, r3.x, r3.y
        mul r3.x, r1.w, r3.x
        mul r3.x, r3.x, r4.y
        add r3.y, -r3.y, l(1.000000)
        mul r3.y, r3.y, r3.y
        dp3_sat r17.z, r8.xyzx, -r6.xyzx
        dp3_sat r17.x, r8.xyzx, r11.xyzx
        if_nz r3.w
          mad r11.w, -r6.w, r6.w, l(1.000000)
          sqrt r11.w, r11.w
          dp2 r13.w, r17.zzzz, r17.xxxx
          add r16.x, -r3.z, r13.w
          ge r16.y, r16.x, r11.w
          if_nz r16.y
            mov r17.y, l(1.000000)
            mov r15.xyz, r17.xyzx
          else
            mad r16.y, -r16.x, r16.x, l(1.000000)
            rsq r16.y, r16.y
            mul r16.y, r6.w, r16.y
            mad r17.y, -r16.x, r17.x, r17.z
            mul r17.w, r16.y, r17.y
            mul r18.x, r17.z, r17.z
            mad r18.x, r18.x, l(2.000000), l(-1.000000)
            mad r16.x, -r16.x, r3.z, r18.x
            mul r16.x, r16.x, r16.y
            mad r18.x, -r17.x, r17.x, l(1.000000)
            mad r18.x, -r17.z, r17.z, r18.x
            mad r18.x, -r3.z, r3.z, r18.x
            mad_sat r13.w, r13.w, r3.z, r18.x
            sqrt r13.w, r13.w
            mul r13.w, r13.w, r16.y
            mul r18.x, r17.z, r13.w
            add r18.y, r18.x, r18.x
            mad r18.z, r17.x, r11.w, r17.z
            mad r16.y, r16.y, r17.y, r18.z
            mad r17.y, r3.z, r11.w, r16.x
            add r17.y, r17.y, l(1.000000)
            mul r18.w, r13.w, r17.y
            mul r19.x, r16.y, r17.y
            mul r19.y, r16.y, r18.y
            mul r18.x, r18.x, r16.y
            mul r18.x, r18.x, l(0.500000)
            mad r18.x, r18.w, l(-0.500000), r18.x
            mul r18.x, r18.x, r19.x
            mad r19.z, -r18.w, l(2.000000), r19.y
            mul r19.y, r19.z, r19.y
            mad r18.w, r18.w, r18.w, r19.y
            mul r19.y, r17.y, r17.y
            mad r17.y, r3.z, r11.w, r17.y
            mad r17.y, r17.y, l(-0.500000), l(-0.500000)
            mul r17.y, r17.y, r19.x
            mad r17.y, r18.z, r19.y, r17.y
            mad r16.y, r16.y, r17.y, r18.w
            add r17.y, r18.x, r18.x
            mul r18.z, r18.x, r18.x
            mad r18.z, r16.y, r16.y, r18.z
            div r17.y, r17.y, r18.z
            mul r16.y, r16.y, r17.y
            mad r17.y, -r17.y, r18.x, l(1.000000)
            mul r13.w, r13.w, r16.y
            mad r13.w, r17.y, r17.w, r13.w
            mul r16.y, r18.y, r16.y
            mad r16.x, r17.y, r16.x, r16.y
            mad r15.x, r17.x, r11.w, r13.w
            mad r3.z, r3.z, r11.w, r16.x
            mad r11.w, r3.z, l(2.000000), l(2.000000)
            rsq r11.w, r11.w
            add r13.w, r17.z, r15.x
            mul_sat r15.y, r11.w, r13.w
            mad_sat r15.z, r11.w, r3.z, r11.w
          endif
        else
          mad r9.xyz, r9.xyzx, r1.yyyy, -r6.xyzx
          dp3 r1.y, r9.xyzx, r9.xyzx
          rsq r1.y, r1.y
          mul r9.xyz, r1.yyyy, r9.xyzx
          dp3_sat r15.y, r8.xyzx, r9.xyzx
          mov r15.x, r17.x
        endif
        add r1.y, r17.z, l(0.000010)
        min r1.y, r1.y, l(1.000000)
        mad r3.z, -r15.z, l(0.220000), l(0.630000)
        mad r3.z, r3.z, r15.z, l(-0.745000)
        mul r9.x, r15.y, r3.z
        mad_sat r1.y, r1.y, l(0.666666687), -r9.x
        mad_sat r9.x, r15.x, l(0.666666687), -r9.x
        mad_sat r3.z, r15.z, l(0.666666687), -r3.z
        lt r9.y, l(0.000000), r9.x
        lt r9.z, l(0.000000), r1.y
        and r9.y, r9.z, r9.y
        rcp r9.z, r1.y
        rcp r11.w, r9.x
        add r9.z, r9.z, r11.w
        lt r11.w, l(0.000000), r2.x
        mul r17.xyz, r5.xyzx, l(0.318309873, 0.318309873, 0.318309873, 0.000000)
        log r17.xyz, r17.xyzx
        mul r17.xyz, r17.xyzx, l(-0.346573591, -0.346573591, -0.346573591, 0.000000)
        add r9.z, r9.z, l(-2.000000)
        max r9.z, r9.z, l(0.000000)
        mul r17.xyz, r9.zzzz, r17.xyzx
        mul r17.xyz, r17.xyzx, l(-1.442695, -1.442695, -1.442695, 0.000000)
        exp r17.xyz, r17.xyzx
        min r17.xyz, r17.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
        add r17.xyz, r17.xyzx, l(-1.000000, -1.000000, -1.000000, 0.000000)
        mad r17.xyz, r2.xxxx, r17.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
        movc r17.xyz, r11.wwww, r17.xyzx, l(1.000000,1.000000,1.000000,0)
        and r17.xyz, r9.yyyy, r17.xyzx
        mul r9.y, r2.z, r2.z
        mad r9.z, r3.z, l(3.600000), l(0.400000)
        div r9.z, r12.w, r9.z
        mad r9.z, r2.z, r2.z, r9.z
        min r9.z, r9.z, l(1.000000)
        movc r16.z, r10.w, r9.z, r9.y
        ishr r9.y, r16.z, l(1)
        iadd r9.y, r9.y, l(0x1fbd1df5)
        mad r9.y, r9.y, l(3.000000), r6.w
        mul r0.w, r0.w, r9.y
        add r9.y, r3.z, l(0.001000)
        div r0.w, r0.w, r9.y
        add r16.x, r0.w, r16.z
        div r16.y, r16.z, r16.x
        movc r16.xy, r3.wwww, r16.xyxx, r16.zwzz
        ishr r0.w, r16.x, l(1)
        iadd r0.w, r0.w, l(0x1fbd1df5)
        mad r0.w, r0.w, l(3.000000), r14.w
        mul r0.w, r0.w, r15.w
        div r0.w, r0.w, r9.y
        add r0.w, r0.w, r16.x
        div r0.w, r16.x, r0.w
        sqrt r0.w, r0.w
        mul r0.w, r0.w, r16.y
        movc r0.w, r9.w, r0.w, r16.y
        mul r9.yzw, r0.wwww, r0.xxyz
        mul r9.yzw, r9.yyzw, l(0.000000, 0.318309873, 0.318309873, 0.318309873)
        mul r3.w, r3.y, r9.x
        mad r16.xyw, r3.wwww, r17.xyxz, -r15.xxxx
        mad r16.xyw, r4.yyyy, r16.xyxw, r15.xxxx
        mul r12.xyz, r9.yzwy, r16.xywx
        mad r3.w, r15.y, r16.z, -r15.y
        mad r3.w, r3.w, r15.y, l(1.000000)
        mul r3.w, r3.w, r3.w
        mul r3.w, r3.w, l(3.14159274)
        div r3.w, r16.z, r3.w
        sqrt r9.y, r16.z
        add r9.z, -r9.y, l(1.000000)
        mad r9.w, r1.y, r9.z, r9.y
        mad r9.y, r9.x, r9.z, r9.y
        mul r1.y, r1.y, r9.y
        mad r1.y, r9.x, r9.w, r1.y
        rcp r1.y, r1.y
        mul r1.y, r1.y, l(0.500000)
        add r3.z, -r3.z, l(1.000000)
        mul r9.y, r3.z, r3.z
        mul r9.y, r9.y, r9.y
        mul r9.z, r3.z, r9.y
        mul_sat r9.w, r10.y, l(50.000000)
        mad r3.z, -r9.y, r3.z, l(1.000000)
        mul r15.yzw, r10.xxyz, r3.zzzz
        mad r9.yzw, r9.wwww, r9.zzzz, r15.yyzw
        mul r0.w, r0.w, r3.w
        mul r0.w, r1.y, r0.w
        mul r9.yzw, r9.yyzw, r0.wwww
        mul r3.yzw, r3.yyyy, r17.xxyz
        mad r3.yzw, r3.yyzw, r9.xxxx, -r15.xxxx
        mad r3.yzw, r4.yyyy, r3.yyzw, r15.xxxx
        mul r3.yzw, r3.yyzw, r9.yyzw
        mad r13.xyz, r3.xxxx, l(0.500000, 0.500000, 0.500000, 0.000000), r3.yzwy
        mov r14.xyz, l(0,0,0,0)
        break
        case l(5)
        dp3 r0.w, r8.xyzx, r11.xyzx
        dp3 r1.y, r8.xyzx, -r6.xyzx
        dp3 r3.x, -r6.xyzx, r11.xyzx
        lt r3.y, l(0.000000), r6.w
        if_nz r3.y
          mad r3.z, -r6.w, r6.w, l(1.000000)
          sqrt r3.z, r3.z
          dp2 r3.w, r1.yyyy, r0.wwww
          add r9.x, -r3.x, r3.w
          ge r9.y, r9.x, r3.z
          if_nz r9.y
            mov r9.y, l(1.000000)
            mov r9.z, |r1.y|
          else
            mad r9.w, -r9.x, r9.x, l(1.000000)
            rsq r9.w, r9.w
            mul r9.w, r6.w, r9.w
            mad r10.w, -r9.x, r0.w, r1.y
            mul r11.w, r9.w, r10.w
            mul r12.w, r1.y, r1.y
            mad r12.w, r12.w, l(2.000000), l(-1.000000)
            mad r9.x, -r9.x, r3.x, r12.w
            mul r9.x, r9.x, r9.w
            mad r12.w, -r0.w, r0.w, l(1.000000)
            mad r12.w, -r1.y, r1.y, r12.w
            mad r12.w, -r3.x, r3.x, r12.w
            mad_sat r3.w, r3.w, r3.x, r12.w
            sqrt r3.w, r3.w
            mul r3.w, r3.w, r9.w
            mul r12.w, r1.y, r3.w
            add r13.w, r12.w, r12.w
            mad r14.w, r0.w, r3.z, r1.y
            mad r9.w, r9.w, r10.w, r14.w
            mad r10.w, r3.x, r3.z, r9.x
            add r10.w, r10.w, l(1.000000)
            mul r15.x, r3.w, r10.w
            mul r15.y, r9.w, r10.w
            mul r15.z, r9.w, r13.w
            mul r12.w, r12.w, r9.w
            mul r12.w, r12.w, l(0.500000)
            mad r12.w, r15.x, l(-0.500000), r12.w
            mul r12.w, r12.w, r15.y
            mad r15.w, -r15.x, l(2.000000), r15.z
            mul r15.z, r15.w, r15.z
            mad r15.x, r15.x, r15.x, r15.z
            mul r15.z, r10.w, r10.w
            mad r10.w, r3.x, r3.z, r10.w
            mad r10.w, r10.w, l(-0.500000), l(-0.500000)
            mul r10.w, r10.w, r15.y
            mad r10.w, r14.w, r15.z, r10.w
            mad r9.w, r9.w, r10.w, r15.x
            add r10.w, r12.w, r12.w
            mul r14.w, r12.w, r12.w
            mad r14.w, r9.w, r9.w, r14.w
            div r10.w, r10.w, r14.w
            mul r9.w, r9.w, r10.w
            mad r10.w, -r10.w, r12.w, l(1.000000)
            mul r3.w, r3.w, r9.w
            mad r3.w, r10.w, r11.w, r3.w
            mul r9.w, r13.w, r9.w
            mad r9.x, r10.w, r9.x, r9.w
            mad r3.w, r0.w, r3.z, r3.w
            mad r3.z, r3.x, r3.z, r9.x
            mad r9.x, r3.z, l(2.000000), l(2.000000)
            rsq r9.x, r9.x
            add r3.w, r1.y, r3.w
            mul_sat r9.y, r9.x, r3.w
            mad_sat r9.z, r9.x, r3.z, r9.x
          endif
        else
          mad r3.z, r3.x, l(2.000000), l(2.000000)
          rsq r3.z, r3.z
          add r0.w, r0.w, r1.y
          mul_sat r9.y, r3.z, r0.w
          mad_sat r9.z, r3.z, r3.x, r3.z
        endif
        add r0.w, |r1.y|, l(0.000010)
        min r0.w, r0.w, l(1.000000)
        mul r3.x, r4.x, l(10.000000)
        mad r1.y, r4.y, l(255.000000), l(0.500000)
        ftou r15.y, r1.y
        mov r15.xzw, l(5,0,0,0)
        ld_indexable(texture2d)(float,float,float,float) r15.xyz, r15.xyzw, t8.xyzw
        dp2_sat r1.y, r15.xxxx, r1.zzzz
        max r1.y, r1.y, l(0.020000)
        dp2_sat r3.z, r15.yyyy, r1.zzzz
        mov_sat r3.x, r3.x
        add r1.y, r1.y, l(-1.000000)
        mad r1.y, r3.x, r1.y, l(1.000000)
        add r3.z, r3.z, l(-1.000000)
        mad r3.x, r3.x, r3.z, l(1.000000)
        mul r3.z, r9.z, r9.z
        dp2 r3.z, r3.zzzz, r1.zzzz
        add r3.z, r3.z, l(-0.500000)
        add r3.w, -r0.w, l(1.000000)
        mul r9.x, r3.w, r3.w
        mul r9.x, r9.x, r9.x
        mul r3.w, r3.w, r9.x
        mad r3.w, r3.z, r3.w, l(1.000000)
        add r9.x, -r1.w, l(1.000000)
        mul r9.w, r9.x, r9.x
        mul r9.w, r9.w, r9.w
        mul r9.x, r9.x, r9.w
        mad r3.z, r3.z, r9.x, l(1.000000)
        mul r3.xz, r3.xxwx, r3.xxzx
        mul r3.z, r3.z, l(0.318309873)
        mul r15.xyw, r0.xyxz, r3.zzzz
        mul r12.xyz, r1.wwww, r15.xywx
        mul r1.y, r1.y, r1.y
        mul r3.z, r1.y, r1.y
        mul r3.w, r3.x, r3.x
        lt r9.x, l(0.000000), r8.w
        mul r9.w, r8.w, r8.w
        mad r10.w, r9.z, l(3.600000), l(0.400000)
        div r9.w, r9.w, r10.w
        mad r1.y, r1.y, r1.y, r9.w
        min r1.y, r1.y, l(1.000000)
        movc r16.x, r9.x, r1.y, r3.z
        mul r1.y, r6.w, l(0.250000)
        ishr r3.z, r16.x, l(1)
        iadd r3.z, r3.z, l(0x1fbd1df5)
        mad r3.z, r3.z, l(3.000000), r6.w
        mul r3.z, r1.y, r3.z
        add r10.w, r9.z, l(0.001000)
        div r3.z, r3.z, r10.w
        add r15.x, r3.z, r16.x
        div r15.y, r16.x, r15.x
        mov r16.yw, l(0,1.000000,0,1.000000)
        movc r15.xy, r3.yyyy, r15.xyxx, r16.xyxx
        lt r3.z, r7.z, l(1.000000)
        add r11.w, -r7.z, l(1.000100)
        add r12.w, r7.z, l(1.000000)
        div r11.w, r11.w, r12.w
        sqrt r11.w, r11.w
        mul r12.w, r11.w, l(0.250000)
        ishr r13.w, r15.x, l(1)
        iadd r13.w, r13.w, l(0x1fbd1df5)
        mad r13.w, r13.w, l(3.000000), r11.w
        mul r13.w, r12.w, r13.w
        div r13.w, r13.w, r10.w
        add r13.w, r13.w, r15.x
        div r13.w, r15.x, r13.w
        sqrt r13.w, r13.w
        mul r13.w, r13.w, r15.y
        movc r13.w, r3.z, r13.w, r15.y
        mad r3.x, r3.x, r3.x, r9.w
        min r3.x, r3.x, l(1.000000)
        movc r16.z, r9.x, r3.x, r3.w
        ishr r3.x, r16.z, l(1)
        iadd r3.x, r3.x, l(0x1fbd1df5)
        mad r3.x, r3.x, l(3.000000), r6.w
        mul r1.y, r1.y, r3.x
        div r1.y, r1.y, r10.w
        add r15.x, r1.y, r16.z
        div r15.y, r16.z, r15.x
        movc r3.xy, r3.yyyy, r15.xyxx, r16.zwzz
        ishr r1.y, r3.x, l(1)
        iadd r1.y, r1.y, l(0x1fbd1df5)
        mad r1.y, r1.y, l(3.000000), r11.w
        mul r1.y, r1.y, r12.w
        div r1.y, r1.y, r10.w
        add r1.y, r1.y, r3.x
        div r1.y, r3.x, r1.y
        sqrt r1.y, r1.y
        mul r1.y, r1.y, r3.y
        movc r1.y, r3.z, r1.y, r3.y
        mad r3.xy, r9.yyyy, r16.xzxx, -r9.yyyy
        mad r3.xy, r3.xyxx, r9.yyyy, l(1.000000, 1.000000, 0.000000, 0.000000)
        mul r3.xy, r3.xyxx, r3.xyxx
        mul r3.xy, r3.xyxx, l(3.14159274, 3.14159274, 0.000000, 0.000000)
        div r3.xy, r16.xzxx, r3.xyxx
        mul r3.x, r13.w, r3.x
        mad r1.y, r3.y, r1.y, -r3.x
        mad r1.y, r15.z, r1.y, r3.x
        mad r3.x, r0.w, r7.w, r2.z
        mad r3.y, r1.w, r7.w, r2.z
        mul r0.w, r0.w, r3.y
        mad r0.w, r1.w, r3.x, r0.w
        rcp r0.w, r0.w
        mul r0.w, r0.w, r1.y
        add r1.y, -r9.z, l(1.000000)
        mul r3.x, r1.y, r1.y
        mul r3.x, r3.x, r3.x
        mul r3.y, r1.y, r3.x
        mul_sat r3.z, r10.y, l(50.000000)
        mad r1.y, -r3.x, r1.y, l(1.000000)
        mul r9.xyz, r10.xyzx, r1.yyyy
        mad r3.xyz, r3.zzzz, r3.yyyy, r9.xyzx
        mul r0.w, r0.w, l(0.500000)
        mul r3.xyz, r3.xyzx, r0.wwww
        mul r13.xyz, r1.wwww, r3.xyzx
        mov r14.xyz, l(0,0,0,0)
        break
        case l(6)
        dp3 r0.w, r8.xyzx, r11.xyzx
        dp3 r1.y, r8.xyzx, -r6.xyzx
        dp3 r3.x, -r6.xyzx, r11.xyzx
        lt r3.y, l(0.000000), r6.w
        if_nz r3.y
          mad r3.z, -r6.w, r6.w, l(1.000000)
          sqrt r3.z, r3.z
          dp2 r3.w, r1.yyyy, r0.wwww
          add r7.w, -r3.x, r3.w
          ge r9.x, r7.w, r3.z
          if_nz r9.x
            mov r9.x, l(1.000000)
            mov r9.y, |r1.y|
          else
            mad r9.z, -r7.w, r7.w, l(1.000000)
            rsq r9.z, r9.z
            mul r9.z, r6.w, r9.z
            mad r9.w, -r7.w, r0.w, r1.y
            mul r10.w, r9.w, r9.z
            mul r11.w, r1.y, r1.y
            mad r11.w, r11.w, l(2.000000), l(-1.000000)
            mad r7.w, -r7.w, r3.x, r11.w
            mul r7.w, r7.w, r9.z
            mad r11.w, -r0.w, r0.w, l(1.000000)
            mad r11.w, -r1.y, r1.y, r11.w
            mad r11.w, -r3.x, r3.x, r11.w
            mad_sat r3.w, r3.w, r3.x, r11.w
            sqrt r3.w, r3.w
            mul r3.w, r3.w, r9.z
            mul r11.w, r1.y, r3.w
            add r12.w, r11.w, r11.w
            mad r13.w, r0.w, r3.z, r1.y
            mad r9.z, r9.z, r9.w, r13.w
            mad r9.w, r3.x, r3.z, r7.w
            add r9.w, r9.w, l(1.000000)
            mul r14.w, r3.w, r9.w
            mul r15.x, r9.w, r9.z
            mul r15.y, r9.z, r12.w
            mul r11.w, r11.w, r9.z
            mul r11.w, r11.w, l(0.500000)
            mad r11.w, r14.w, l(-0.500000), r11.w
            mul r11.w, r11.w, r15.x
            mad r15.z, -r14.w, l(2.000000), r15.y
            mul r15.y, r15.z, r15.y
            mad r14.w, r14.w, r14.w, r15.y
            mul r15.y, r9.w, r9.w
            mad r9.w, r3.x, r3.z, r9.w
            mad r9.w, r9.w, l(-0.500000), l(-0.500000)
            mul r9.w, r9.w, r15.x
            mad r9.w, r13.w, r15.y, r9.w
            mad r9.z, r9.z, r9.w, r14.w
            add r9.w, r11.w, r11.w
            mul r13.w, r11.w, r11.w
            mad r13.w, r9.z, r9.z, r13.w
            div r9.w, r9.w, r13.w
            mul r9.z, r9.z, r9.w
            mad r9.w, -r9.w, r11.w, l(1.000000)
            mul r3.w, r3.w, r9.z
            mad r3.w, r9.w, r10.w, r3.w
            mul r9.z, r12.w, r9.z
            mad r7.w, r9.w, r7.w, r9.z
            mad r3.w, r0.w, r3.z, r3.w
            mad r3.z, r3.x, r3.z, r7.w
            mad r7.w, r3.z, l(2.000000), l(2.000000)
            rsq r7.w, r7.w
            add r3.w, r1.y, r3.w
            mul_sat r9.x, r7.w, r3.w
            mad_sat r9.y, r7.w, r3.z, r7.w
          endif
        else
          mad r3.z, r3.x, l(2.000000), l(2.000000)
          rsq r3.z, r3.z
          add r3.w, r0.w, r1.y
          mul_sat r9.x, r3.z, r3.w
          mad_sat r9.y, r3.z, r3.x, r3.z
        endif
        add r1.y, |r1.y|, l(0.000010)
        min r1.y, r1.y, l(1.000000)
        mul r15.xyz, r0.xyzx, r1.wwww
        mul r12.xyz, r15.xyzx, l(0.318309873, 0.318309873, 0.318309873, 0.000000)
        mul r3.z, r2.z, r2.z
        lt r3.w, l(0.000000), r8.w
        mul r7.w, r8.w, r8.w
        mad r9.z, r9.y, l(3.600000), l(0.400000)
        div r7.w, r7.w, r9.z
        mad r7.w, r2.z, r2.z, r7.w
        min r7.w, r7.w, l(1.000000)
        movc r15.x, r3.w, r7.w, r3.z
        mul r3.z, r6.w, l(0.250000)
        ishr r3.w, r15.x, l(1)
        iadd r3.w, r3.w, l(0x1fbd1df5)
        mad r3.w, r3.w, l(3.000000), r6.w
        mul r3.z, r3.w, r3.z
        add r3.w, r9.y, l(0.001000)
        div r3.z, r3.z, r3.w
        add r16.x, r3.z, r15.x
        div r16.y, r15.x, r16.x
        mov r15.y, l(1.000000)
        movc r3.yz, r3.yyyy, r16.xxyx, r15.xxyx
        lt r7.w, r7.z, l(1.000000)
        add r9.z, -r7.z, l(1.000100)
        add r9.w, r7.z, l(1.000000)
        div r9.z, r9.z, r9.w
        sqrt r9.z, r9.z
        mul r9.w, r9.z, l(0.250000)
        ishr r10.w, r3.y, l(1)
        iadd r10.w, r10.w, l(0x1fbd1df5)
        mad r9.z, r10.w, l(3.000000), r9.z
        mul r9.z, r9.z, r9.w
        div r3.w, r9.z, r3.w
        add r3.w, r3.w, r3.y
        div r3.y, r3.y, r3.w
        sqrt r3.y, r3.y
        mul r3.y, r3.y, r3.z
        movc r3.y, r7.w, r3.y, r3.z
        mad r3.z, r9.x, r15.x, -r9.x
        mad r3.z, r3.z, r9.x, l(1.000000)
        mul r3.z, r3.z, r3.z
        mul r3.z, r3.z, l(3.14159274)
        div r3.z, r15.x, r3.z
        mul r3.y, r3.y, r3.z
        sqrt r3.z, r15.x
        add r3.w, -r3.z, l(1.000000)
        mad r7.w, r1.y, r3.w, r3.z
        mad r3.z, r1.w, r3.w, r3.z
        mul r1.y, r1.y, r3.z
        mad r1.y, r1.w, r7.w, r1.y
        rcp r1.y, r1.y
        mul r1.y, r1.y, r3.y
        add r3.y, -r9.y, l(1.000000)
        mul r3.z, r3.y, r3.y
        mul r3.z, r3.z, r3.z
        mul r3.w, r3.y, r3.z
        mul_sat r7.w, r10.y, l(50.000000)
        mad r3.y, -r3.z, r3.y, l(1.000000)
        mul r9.xyz, r10.xyzx, r3.yyyy
        mad r3.yzw, r7.wwww, r3.wwww, r9.xxyz
        mul r1.y, r1.y, l(0.500000)
        mul r3.yzw, r3.yyzw, r1.yyyy
        mul r13.xyz, r1.wwww, r3.yzwy
        mul r3.yzw, r4.yyzw, r4.yyzw
        add r0.w, -r0.w, l(0.500000)
        mul_sat r0.w, r0.w, l(0.444444448)
        mov_sat r3.x, -r3.x
        mul r1.y, r3.x, r3.x
        mad r1.y, r1.y, l(-0.640000), l(1.000000)
        mul r1.y, r1.y, r1.y
        mul r1.y, r1.y, l(3.14159274)
        div r1.y, l(0.360000), r1.y
        mul r0.w, r0.w, r1.y
        mul r14.xyz, r3.yzwy, r0.wwww
        break
        case l(7)
        max r0.w, r1.z, l(0.00392156886)
        min r0.w, r0.w, l(1.000000)
        dp3 r1.y, -r6.xyzx, r11.xyzx
        dp3 r1.z, r8.xyzx, r11.xyzx
        dp3 r3.x, r8.xyzx, -r6.xyzx
        mad r3.y, |r3.x|, l(-0.156583), l(1.57079637)
        add r3.z, -|r3.x|, l(1.000000)
        sqrt r3.z, r3.z
        mul r3.w, r3.z, r3.y
        ge r7.w, r3.x, l(0.000000)
        mad r3.y, -r3.y, r3.z, l(3.14159274)
        movc r3.y, r7.w, r3.w, r3.y
        mad r3.z, |r1.z|, l(-0.156583), l(1.57079637)
        add r3.w, -|r1.z|, l(1.000000)
        sqrt r7.w, r3.w
        mul r9.x, r3.z, r7.w
        ge r9.y, r1.z, l(0.000000)
        mad r3.z, -r3.z, r7.w, l(3.14159274)
        movc r3.z, r9.y, r9.x, r3.z
        add r3.yz, -r3.yyzy, l(0.000000, 1.57079637, 1.57079637, 0.000000)
        add r3.y, -r3.z, r3.y
        mul r3.y, |r3.y|, l(0.500000)
        sincos null, r3.y, r3.y
        mad r9.xyz, -r1.zzzz, r8.xyzx, r11.xyzx
        mad r15.xyz, -r3.xxxx, r8.xyzx, -r6.xyzx
        dp3 r3.z, r9.xyzx, r15.xyzx
        dp3 r7.w, r9.xyzx, r9.xyzx
        dp3 r9.x, r15.xyzx, r15.xyzx
        mad r7.w, r7.w, r9.x, l(0.000100)
        rsq r7.w, r7.w
        mul r3.z, r3.z, r7.w
        mad r9.yzw, r3.zzzz, l(0.000000, 0.500000, -3.650000, 17.000000), l(0.000000, 0.500000, -3.980000, -16.780001)
        mov_sat r9.y, r9.y
        sqrt r7.w, r9.y
        div r16.xy, l(1.190000, 0.800000, 0.000000, 0.000000), r3.yyyy
        mad r9.y, r3.y, l(0.360000), r16.x
        mul r0.w, r0.w, r0.w
        mul r16.xzw, r0.wwww, l(0.500000, 0.000000, 1.25331414, 5.01325655)
        add r10.w, r0.w, r0.w
        mul r11.w, r7.w, l(0.997551)
        mad r12.w, -r3.x, r3.x, l(1.000000)
        sqrt r12.w, r12.w
        mul r13.w, r3.x, l(-0.0699428469)
        mad r11.w, r11.w, r12.w, r13.w
        mul r0.w, r7.w, r0.w
        mul r17.xy, r0.wwww, l(1.41421354, 3.54490757, 0.000000, 0.000000)
        add r0.w, r1.z, r3.x
        mad r1.z, -r11.w, l(-0.139885694), r0.w
        mul r1.z, r1.z, r1.z
        mul r1.z, r1.z, l(-0.500000)
        mul r3.x, r17.x, r17.x
        div r1.z, r1.z, r3.x
        mul r1.z, r1.z, l(1.442695)
        exp r1.z, r1.z
        div r1.z, r1.z, r17.y
        mul r1.z, r7.w, r1.z
        mad_sat r3.x, r1.y, l(0.500000), l(0.500000)
        sqrt r3.x, r3.x
        add r3.x, -r3.x, l(1.000000)
        mul r11.w, r3.x, r3.x
        mul r11.w, r11.w, r11.w
        mul r3.x, r3.x, r11.w
        mad r3.x, r3.x, l(0.953479409), l(0.0465205684)
        mul r1.z, r1.z, r3.x
        mul r1.z, r5.w, r1.z
        mul r1.z, r1.z, l(0.500000)
        mov_sat r1.y, -r1.y
        add r3.x, r4.w, l(-1.000000)
        mad r1.y, r1.y, r3.x, l(1.000000)
        add r17.xy, r0.wwww, l(-0.035000, -0.140000, 0.000000, 0.000000)
        mul r17.xy, r17.xyxx, r17.xyxx
        mul r17.xy, r17.xyxx, l(-0.500000, -0.500000, 0.000000, 0.000000)
        mul r0.w, r16.x, r16.x
        div r0.w, r17.x, r0.w
        mul r0.w, r0.w, l(1.442695)
        exp r0.w, r0.w
        div r0.w, r0.w, r16.z
        div r3.x, l(1.000000, 1.000000, 1.000000, 1.000000), r9.y
        mad r3.z, -r3.z, l(0.800000), l(0.600000)
        mad r3.z, r3.x, r3.z, l(1.000000)
        mul r3.z, r3.z, r7.w
        mad r7.w, -r3.z, r3.z, l(1.000000)
        max r7.w, r7.w, l(0.000000)
        sqrt r7.w, r7.w
        mad r7.w, -r3.y, r7.w, l(1.000000)
        mul r9.y, r7.w, r7.w
        mul r9.y, r9.y, r9.y
        mul r7.w, r7.w, r9.y
        mad r7.w, r7.w, l(0.953479409), l(0.0465205684)
        add r7.w, -r7.w, l(1.000000)
        mul r7.w, r7.w, r7.w
        mul r3.x, r3.x, r3.z
        mad r3.x, -r3.x, r3.x, l(1.000000)
        sqrt r3.x, r3.x
        mul r3.x, r3.x, l(0.500000)
        div r3.x, r3.x, r3.y
        log r17.xzw, r5.xxyz
        mul r18.xyz, r3.xxxx, r17.xzwx
        exp r18.xyz, r18.xyzx
        mul r3.xz, r9.zzwz, l(1.442695, 0.000000, 1.442695, 0.000000)
        exp r3.xz, r3.xxzx
        mul r0.w, r0.w, r3.x
        mul r0.w, r7.w, r0.w
        mul r9.yzw, r18.xxyz, r0.wwww
        mul r9.yzw, r4.wwww, r9.yyzw
        mad r9.yzw, r1.zzzz, r1.yyyy, r9.yyzw
        mul r0.w, r10.w, r10.w
        div r0.w, r17.y, r0.w
        mul r0.w, r0.w, l(1.442695)
        exp r0.w, r0.w
        div r0.w, r0.w, r16.w
        mad r1.y, -r3.y, l(0.500000), l(1.000000)
        mul r1.z, r1.y, r1.y
        mul r1.z, r1.z, r1.z
        mul r1.y, r1.y, r1.z
        mad r1.y, r1.y, l(0.953479409), l(0.0465205684)
        add r1.z, -r1.y, l(1.000000)
        mul r1.z, r1.z, r1.z
        mul r1.y, r1.y, r1.z
        mul r16.xyz, r16.yyyy, r17.xzwx
        exp r16.xyz, r16.xyzx
        mul r0.w, r3.z, r0.w
        mul r0.w, r1.y, r0.w
        mad r3.xyz, r0.wwww, r16.xyzx, r9.yzwy
        rsq r0.w, r9.x
        mul r9.xyz, r0.wwww, r15.xyzx
        dp3 r0.w, r9.xyzx, r11.xyzx
        add r0.w, r0.w, l(1.000000)
        mul_sat r0.w, r0.w, l(0.250000)
        add r1.y, -r0.w, r3.w
        mad r0.w, r1.y, l(0.330000), r0.w
        mul r0.w, r0.w, r2.x
        mul r0.w, r0.w, l(0.318309873)
        dp3 r1.y, r5.xyzx, l(0.300000, 0.590000, 0.110000, 0.000000)
        div r9.xyz, r5.xyzx, r1.yyyy
        add r1.y, -r7.y, l(1.000000)
        log r9.xyz, r9.xyzx
        mul r9.xyz, r1.yyyy, r9.xyzx
        exp r9.xyz, r9.xyzx
        sqrt r5.xyz, r5.xyzx
        mul r5.xyz, r0.wwww, r5.xyzx
        mad r3.xyz, r5.xyzx, r9.xyzx, r3.xyzx
        min r14.xyz, -r3.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
        mov r12.xyz, l(0,0,0,0)
        mov r13.xyz, l(0,0,0,0)
        mov r14.xyz, -r14.xyzx
        break
        case l(8)
        mul r3.xyz, r4.yzwy, r4.yzwy
        mov_sat r4.x, r4.x
        dp3 r0.w, r8.xyzx, r11.xyzx
        dp3 r1.y, r8.xyzx, -r6.xyzx
        dp3 r1.z, -r6.xyzx, r11.xyzx
        lt r2.x, l(0.000000), r6.w
        if_nz r2.x
          mad r3.w, -r6.w, r6.w, l(1.000000)
          sqrt r3.w, r3.w
          dp2 r4.y, r1.yyyy, r0.wwww
          add r5.x, -r1.z, r4.y
          ge r5.y, r5.x, r3.w
          if_nz r5.y
            mov r5.y, l(1.000000)
            mov r5.z, |r1.y|
          else
            mad r7.w, -r5.x, r5.x, l(1.000000)
            rsq r7.w, r7.w
            mul r7.w, r6.w, r7.w
            mad r9.x, -r5.x, r0.w, r1.y
            mul r9.y, r7.w, r9.x
            mul r9.z, r1.y, r1.y
            mad r9.z, r9.z, l(2.000000), l(-1.000000)
            mad r5.x, -r5.x, r1.z, r9.z
            mul r5.x, r5.x, r7.w
            mad r9.z, -r0.w, r0.w, l(1.000000)
            mad r9.z, -r1.y, r1.y, r9.z
            mad r9.z, -r1.z, r1.z, r9.z
            mad_sat r4.y, r4.y, r1.z, r9.z
            sqrt r4.y, r4.y
            mul r4.y, r4.y, r7.w
            mul r9.z, r1.y, r4.y
            add r9.w, r9.z, r9.z
            mad r10.w, r0.w, r3.w, r1.y
            mad r7.w, r7.w, r9.x, r10.w
            mad r9.x, r1.z, r3.w, r5.x
            add r9.x, r9.x, l(1.000000)
            mul r11.w, r4.y, r9.x
            mul r12.w, r7.w, r9.x
            mul r13.w, r7.w, r9.w
            mul r9.z, r9.z, r7.w
            mul r9.z, r9.z, l(0.500000)
            mad r9.z, r11.w, l(-0.500000), r9.z
            mad r14.w, -r11.w, l(2.000000), r13.w
            mul r13.w, r13.w, r14.w
            mad r11.w, r11.w, r11.w, r13.w
            mul r13.w, r9.x, r9.x
            mad r9.x, r1.z, r3.w, r9.x
            mad r9.x, r9.x, l(-0.500000), l(-0.500000)
            mul r9.xz, r9.xxzx, r12.wwww
            mad r9.x, r10.w, r13.w, r9.x
            mad r7.w, r7.w, r9.x, r11.w
            add r9.x, r9.z, r9.z
            mul r10.w, r9.z, r9.z
            mad r10.w, r7.w, r7.w, r10.w
            div r9.x, r9.x, r10.w
            mul r7.w, r7.w, r9.x
            mad r9.x, -r9.x, r9.z, l(1.000000)
            mul r4.y, r4.y, r7.w
            mad r4.y, r9.x, r9.y, r4.y
            mul r7.w, r9.w, r7.w
            mad r5.x, r9.x, r5.x, r7.w
            mad r4.y, r0.w, r3.w, r4.y
            mad r3.w, r1.z, r3.w, r5.x
            mad r5.x, r3.w, l(2.000000), l(2.000000)
            rsq r5.x, r5.x
            add r4.y, r1.y, r4.y
            mul_sat r5.y, r5.x, r4.y
            mad_sat r5.z, r5.x, r3.w, r5.x
          endif
        else
          mad r3.w, r1.z, l(2.000000), l(2.000000)
          rsq r3.w, r3.w
          add r0.w, r0.w, r1.y
          mul_sat r5.y, r3.w, r0.w
          mad_sat r5.z, r3.w, r1.z, r3.w
        endif
        add r0.w, |r1.y|, l(0.000010)
        min r0.w, r0.w, l(1.000000)
        mul r1.y, r2.z, r2.z
        lt r1.z, l(0.000000), r8.w
        mul r3.w, r8.w, r8.w
        mad r4.y, r5.z, l(3.600000), l(0.400000)
        div r3.w, r3.w, r4.y
        mad r3.w, r2.z, r2.z, r3.w
        min r3.w, r3.w, l(1.000000)
        movc r9.x, r1.z, r3.w, r1.y
        mul r1.z, r6.w, l(0.250000)
        ishr r3.w, r9.x, l(1)
        iadd r3.w, r3.w, l(0x1fbd1df5)
        mad r3.w, r3.w, l(3.000000), r6.w
        mul r1.z, r1.z, r3.w
        add r3.w, r5.z, l(0.001000)
        div r1.z, r1.z, r3.w
        add r15.x, r1.z, r9.x
        div r15.y, r9.x, r15.x
        mov r9.y, l(1.000000)
        movc r9.yz, r2.xxxx, r15.xxyx, r9.xxyx
        lt r1.z, r7.z, l(1.000000)
        add r2.x, -r7.z, l(1.000100)
        add r4.y, r7.z, l(1.000000)
        div r2.x, r2.x, r4.y
        sqrt r2.x, r2.x
        mul r4.y, r2.x, l(0.250000)
        ishr r5.x, r9.y, l(1)
        iadd r5.x, r5.x, l(0x1fbd1df5)
        mad r2.x, r5.x, l(3.000000), r2.x
        mul r2.x, r2.x, r4.y
        div r2.x, r2.x, r3.w
        add r2.x, r2.x, r9.y
        div r2.x, r9.y, r2.x
        sqrt r2.x, r2.x
        mul r2.x, r2.x, r9.z
        movc r1.z, r1.z, r2.x, r9.z
        mad r2.x, r5.y, r9.x, -r5.y
        mad r2.x, r2.x, r5.y, l(1.000000)
        mul r2.x, r2.x, r2.x
        mul r2.x, r2.x, l(3.14159274)
        div r2.x, r9.x, r2.x
        mul r1.z, r1.z, r2.x
        sqrt r2.x, r9.x
        add r3.w, -r2.x, l(1.000000)
        mad r4.y, r0.w, r3.w, r2.x
        mad r2.x, r1.w, r3.w, r2.x
        mul r2.x, r0.w, r2.x
        mad r2.x, r1.w, r4.y, r2.x
        rcp r2.x, r2.x
        mul r1.z, r1.z, r2.x
        add r2.x, -r5.z, l(1.000000)
        mul r3.w, r2.x, r2.x
        mul r3.w, r3.w, r3.w
        mul r4.y, r2.x, r3.w
        mul_sat r5.x, r10.y, l(50.000000)
        mad r2.x, -r3.w, r2.x, l(1.000000)
        mul r9.xyz, r10.xyzx, r2.xxxx
        mad r9.xyz, r5.xxxx, r4.yyyy, r9.xyzx
        mul r1.z, r1.z, l(0.500000)
        mul r9.xyz, r9.xyzx, r1.zzzz
        mul r9.xyz, r1.wwww, r9.xyzx
        mad r1.z, -r1.y, r5.y, r5.y
        mad r1.z, r1.z, r5.y, r1.y
        mul r3.w, r1.y, l(4.000000)
        mad r5.x, r1.y, l(4.000000), l(1.000000)
        mul r5.x, r5.x, l(3.14159274)
        rcp r5.x, r5.x
        mul r1.y, r1.y, r3.w
        mul r1.z, r1.z, r1.z
        div r1.y, r1.y, r1.z
        add r1.y, r1.y, l(1.000000)
        mul r1.y, r1.y, r5.x
        add r1.z, r0.w, r1.w
        mad r0.w, -r1.w, r0.w, r1.z
        mul r0.w, r0.w, l(4.000000)
        rcp r0.w, r0.w
        mul r1.z, r3.y, l(50.000000)
        min r1.z, r1.z, l(1.000000)
        mul r3.xyz, r3.xyzx, r2.xxxx
        mad r3.xyz, r1.zzzz, r4.yyyy, r3.xyzx
        mul r0.w, r0.w, r1.y
        mul r0.w, r0.w, r1.w
        mul r5.xyz, r0.xyzx, r1.wwww
        mul r12.xyz, r5.xyzx, l(0.318309873, 0.318309873, 0.318309873, 0.000000)
        mad r3.xyz, r0.wwww, r3.xyzx, -r9.xyzx
        mad r13.xyz, r4.xxxx, r3.xyzx, r9.xyzx
        mov r14.xyz, l(0,0,0,0)
        break
        case l(9)
        mad r1.yz, r4.zzwz, l(0.000000, 2.000000, 2.000000, 0.000000), l(0.000000, -1.000000, -1.000000, 0.000000)
        dp2 r0.w, l(1.000000, 1.000000, 0.000000, 0.000000), |r1.yzyy|
        add r3.z, -r0.w, l(1.000000)
        lt r0.w, r3.z, l(0.000000)
        add r4.yz, -|r1.zzyz|, l(0.000000, 1.000000, 1.000000, 0.000000)
        ge r5.xy, r1.yzyy, l(0.000000, 0.000000, 0.000000, 0.000000)
        movc r5.xy, r5.xyxx, l(1.000000,1.000000,0,0), l(-1.000000,-1.000000,0,0)
        mul r4.yz, r4.yyzy, r5.xxyx
        movc r3.xy, r0.wwww, r4.yzyy, r1.yzyy
        dp3 r0.w, r3.xyzx, r3.xyzx
        rsq r0.w, r0.w
        mul r4.yzw, r0.wwww, r3.xxyz
        add r1.y, -r4.x, l(1.000000)
        mul r1.x, r1.x, r1.y
        mad r3.xyz, -r3.xyzx, r0.wwww, -r8.xyzx
        mad r3.xyz, r1.xxxx, r3.xyzx, r4.yzwy
        dp3 r0.w, r3.xyzx, r3.xyzx
        rsq r0.w, r0.w
        mul r3.xyz, r0.wwww, r3.xyzx
        dp3 r0.w, r8.xyzx, r11.xyzx
        dp3 r1.x, r8.xyzx, -r6.xyzx
        dp3 r1.z, -r6.xyzx, r11.xyzx
        lt r2.x, l(0.000000), r6.w
        if_nz r2.x
          mad r3.w, -r6.w, r6.w, l(1.000000)
          sqrt r3.w, r3.w
          dp2 r4.x, r1.xxxx, r0.wwww
          add r4.x, -r1.z, r4.x
          ge r5.x, r4.x, r3.w
          if_nz r5.x
            mov r5.x, l(1.000000)
            mov r5.y, |r1.x|
          else
            mad r5.z, -r4.x, r4.x, l(1.000000)
            rsq r5.z, r5.z
            mul r5.z, r5.z, r6.w
            mad r6.x, -r4.x, r0.w, r1.x
            mul r6.x, r5.z, r6.x
            dp2 r6.y, r1.xxxx, r1.xxxx
            add r6.y, r6.y, l(-1.000000)
            mad r4.x, -r4.x, r1.z, r6.y
            mul r4.x, r4.x, r5.z
            mad r5.z, r0.w, r3.w, r6.x
            mad r3.w, r1.z, r3.w, r4.x
            mad r4.x, r3.w, l(2.000000), l(2.000000)
            rsq r4.x, r4.x
            add r5.z, r1.x, r5.z
            mul_sat r5.x, r4.x, r5.z
            mad_sat r5.y, r4.x, r3.w, r4.x
          endif
        else
          mad r3.w, r1.z, l(2.000000), l(2.000000)
          rsq r3.w, r3.w
          add r0.w, r0.w, r1.x
          mul_sat r5.x, r3.w, r0.w
          mad_sat r5.y, r3.w, r1.z, r3.w
        endif
        add r0.w, |r1.x|, l(0.000010)
        min r0.w, r0.w, l(1.000000)
        mul r1.x, r5.w, l(0.080000)
        add r1.z, -r5.y, l(1.000000)
        mul r3.w, r1.z, r1.z
        mul r3.w, r3.w, r3.w
        mul r4.x, r1.z, r3.w
        mad r1.z, -r3.w, r1.z, l(1.000000)
        mad r1.x, r1.z, r1.x, r4.x
        mul r1.z, r2.z, r2.z
        lt r3.w, l(0.000000), r8.w
        mul r4.x, r8.w, r8.w
        mad r5.z, r5.y, l(3.600000), l(0.400000)
        div r4.x, r4.x, r5.z
        mad r2.z, r2.z, r2.z, r4.x
        min r2.z, r2.z, l(1.000000)
        movc r6.x, r3.w, r2.z, r1.z
        mul r1.z, r6.w, l(0.250000)
        ishr r2.z, r6.x, l(1)
        iadd r2.z, r2.z, l(0x1fbd1df5)
        mad r2.z, r2.z, l(3.000000), r6.w
        mul r1.z, r1.z, r2.z
        add r2.z, r5.y, l(0.001000)
        div r1.z, r1.z, r2.z
        add r8.x, r1.z, r6.x
        div r8.y, r6.x, r8.x
        mov r6.y, l(1.000000)
        movc r5.yz, r2.xxxx, r8.xxyx, r6.xxyx
        lt r1.z, r7.z, l(1.000000)
        add r2.x, -r7.z, l(1.000100)
        add r3.w, r7.z, l(1.000000)
        div r2.x, r2.x, r3.w
        sqrt r2.x, r2.x
        mul r3.w, r2.x, l(0.250000)
        ishr r4.x, r5.y, l(1)
        iadd r4.x, r4.x, l(0x1fbd1df5)
        mad r2.x, r4.x, l(3.000000), r2.x
        mul r2.x, r2.x, r3.w
        div r2.x, r2.x, r2.z
        add r2.x, r2.x, r5.y
        div r2.x, r5.y, r2.x
        sqrt r2.x, r2.x
        mul r2.x, r2.x, r5.z
        movc r1.z, r1.z, r2.x, r5.z
        mad r2.x, r5.x, r6.x, -r5.x
        mad r2.x, r2.x, r5.x, l(1.000000)
        mul r2.x, r2.x, r2.x
        mul r2.x, r2.x, l(3.14159274)
        div r2.x, r6.x, r2.x
        mul r1.z, r1.z, r2.x
        sqrt r2.x, r6.x
        add r2.z, -r2.x, l(1.000000)
        mad r3.w, r0.w, r2.z, r2.x
        mad r2.x, r1.w, r2.z, r2.x
        mul r0.w, r0.w, r2.x
        mad r0.w, r1.w, r3.w, r0.w
        rcp r0.w, r0.w
        mul r0.w, r0.w, l(0.500000)
        mul r1.z, r1.z, r1.w
        mul r0.w, r0.w, r1.z
        mul r13.xyz, r1.xxxx, r0.wwww
        dp3_sat r0.w, r4.yzwy, r11.xyzx
        mad r2.xz, r0.wwww, l(-11.000000, 0.000000, -11.000000, 0.000000), l(12.000000, 0.000000, 13.000000, 0.000000)
        mul r1.z, r2.z, l(0.200000)
        dp3_sat r2.z, r3.xyzx, r11.xyzx
        log r2.z, r2.z
        mul r2.x, r2.z, r2.x
        exp r2.x, r2.x
        mad r1.z, r1.z, r2.x, l(0.800000)
        mad r0.w, r0.w, r1.z, -r1.w
        mad r0.w, r1.y, r0.w, r1.w
        add r1.x, -r1.x, l(1.000000)
        mul r0.w, r0.w, r1.x
        mul r0.xyz, r0.wwww, r0.xyzx
        mul r14.xyz, r0.xyzx, l(0.318309873, 0.318309873, 0.318309873, 0.000000)
        mov r12.xyz, l(0,0,0,0)
        break
        default
        mov r12.xyz, l(0,0,0,0)
        mov r13.xyz, l(0,0,0,0)
        mov r14.xyz, l(0,0,0,0)
        break
      endswitch
      mul r0.xyz, r13.xyzx, cb1[5].wwww
      mul r1.xyz, r2.wwww, cb1[4].xyzx
      mul r2.xzw, r7.xxxx, r1.xxyz
      eq r0.w, cb0[200].z, l(0.000000)
      mul r3.xyz, r2.xzwx, r12.xyzx
      dp3 r1.w, r3.xyzx, l(0.300000, 0.590000, 0.110000, 0.000000)
      and r1.w, r0.w, r1.w
      and r1.w, r1.w, r2.y
      mul r3.xyz, r0.xyzx, r2.xzwx
      mul r0.xyz, r7.yyyy, r1.xyzx
      mul r0.xyz, r0.xyzx, r14.xyzx
      dp3 r1.x, r0.xyzx, l(0.300000, 0.590000, 0.110000, 0.000000)
      add r1.x, r1.x, r1.w
      movc r0.w, r0.w, r1.x, r1.w
      and r0.w, r0.w, r2.y
      mad r1.xyz, r12.xyzx, r2.xzwx, r0.xyzx
    else
      mov r3.xyz, l(0,0,0,0)
      mov r0.w, l(0)
      mov r1.xyz, l(0,0,0,0)
    endif
  else
    mov r3.xyz, l(0,0,0,0)
    mov r0.w, l(0)
    mov r1.xyz, l(0,0,0,0)
  endif
  eq r0.x, cb0[200].z, l(0.000000)
  and r1.w, r0.w, r0.x
  mov r3.w, l(0)
  add r0.xyzw, r1.xyzw, r3.xyzw
else
  mov r0.xyzw, l(0,0,0,0)
endif
mul o0.xyzw, r0.xyzw, cb0[134].yyyy
ret
// Approximately 0 instruction slots used
