//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//   using 3Dmigoto v1.4.1 on Fri Jul  3 11:27:12 2026
//
//
// Buffer Definitions:
//
// cbuffer EntryConstants
// {
//
//   float4 EntryTable[8];              // Offset:    0 Size:   128
//
// }
//
// cbuffer IndexBuffer
// {
//
//   uint IndexOffset;                  // Offset:    0 Size:     4
//
// }
//
// Resource bind info for OutputBuffer
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// OutputBuffer                          UAV  struct         r/w             u0      1
// EntryConstants                    cbuffer      NA          NA            cb0      1
// IndexBuffer                       cbuffer      NA          NA            cb1      1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed | skipOptimization
dcl_constantbuffer CB0[8], dynamicIndexed
dcl_constantbuffer CB1[1], immediateIndexed
dcl_uav_structured u0, 16
dcl_input vThreadID.x
dcl_temps 2
dcl_thread_group 8, 1, 1
iadd r0.x, vThreadID.x, cb1[0].x
mov r1.xyzw, cb0[r0.x + 0].xyzw
mul r1.xyzw, r1.xyzw, l(2.000000, 2.000000, 2.000000, 1.000000)
store_structured u0.x, r0.x, l(0), r1.x
store_structured u0.x, r0.x, l(4), r1.y
store_structured u0.x, r0.x, l(8), r1.z
store_structured u0.x, r0.x, l(12), r1.w
ret
// Approximately 8 instruction slots used
