name: Clang x86

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "docs/**"
      - ".github/workflows/**"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "docs/**"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: windows-latest
    env:
      SCCACHE_GHA_ENABLED: "true"
      SCCACHE_CACHE_SIZE: "5G"
      SCCACHE_C_CUSTOM_CACHE_BUSTER: "${{ github.workflow }}"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up sccache
        uses: mozilla-actions/sccache-action@v0.0.10

      - name: Install ninja-build tool
        uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Configure build for amd64_x86
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64_x86

      - name: Configure CMake (x86)
        run: cmake --preset clang-x86 -DCMAKE_C_COMPILER_LAUNCHER=sccache -DCMAKE_CXX_COMPILER_LAUNCHER=sccache

      - name: Build (x86)
        run: cmake --build --parallel --preset clang-x86-release --verbose

      - name: Build Debug (x86)
        run: cmake --build --parallel --preset clang-x86-debug --verbose

      - name: Install SDK (x86 Release)
        run: cmake --install out/build32/clang-x86 --config Release --component DirectXShaderPatcherSDK --prefix out/install/clang-x86

      - name: Install SDK (x86 Debug)
        run: cmake --install out/build32/clang-x86 --config Debug --component DirectXShaderPatcherSDK --prefix out/install/clang-x86

      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: clang-x86
          path: out/install/clang-x86/
          retention-days: 7

      - name: Show sccache stats
        if: always()
        run: sccache --show-stats
