name: Ninja x64

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "docs/**"
      - ".github/workflows/**"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "docs/**"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - preset: ninja-x64
            suffix: ""
          - preset: ninja-x64-static
            suffix: "-static"
    env:
      SCCACHE_GHA_ENABLED: "true"
      SCCACHE_CACHE_SIZE: "5G"
      SCCACHE_C_CUSTOM_CACHE_BUSTER: "${{ github.workflow }}"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up sccache
        uses: mozilla-actions/sccache-action@v0.0.10

      - name: Install ninja-build tool
        uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Configure build for amd64
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Configure CMake (${{ matrix.preset }})
        run: cmake --preset ${{ matrix.preset }} -DCMAKE_C_COMPILER_LAUNCHER=sccache -DCMAKE_CXX_COMPILER_LAUNCHER=sccache

      - name: Build (${{ matrix.preset }} Release)
        run: cmake --build --parallel --preset ${{ matrix.preset }}-release

      - name: Test (${{ matrix.preset }} Release)
        run: ctest --preset ${{ matrix.preset }}-release --output-on-failure

      - name: Build (${{ matrix.preset }} Debug)
        run: cmake --build --parallel --preset ${{ matrix.preset }}-debug

      - name: Install SDK (${{ matrix.preset }} Release)
        run: cmake --install out/build/${{ matrix.preset }} --config Release --component DirectXShaderPatcherSDK --prefix out/install/${{ matrix.preset }}

      - name: Install SDK (${{ matrix.preset }} Debug)
        run: cmake --install out/build/${{ matrix.preset }} --config Debug --component DirectXShaderPatcherSDK --prefix out/install/${{ matrix.preset }}

      - name: Install CLI (${{ matrix.preset }} Release)
        run: cmake --install out/build/${{ matrix.preset }} --config Release --component DirectXShaderPatcherCLI --prefix out/install/${{ matrix.preset }}

      - name: Install CLI (${{ matrix.preset }} Debug)
        run: cmake --install out/build/${{ matrix.preset }} --config Debug --component DirectXShaderPatcherCLI --prefix out/install/${{ matrix.preset }}

      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ninja-x64${{ matrix.suffix }}
          path: out/install/${{ matrix.preset }}/
          retention-days: 7

      - name: Show sccache stats
        if: always()
        run: sccache --show-stats
